import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { colors, radius } from '../../theme';
import type { Dashboard, User } from '../../types';

export type AppTab = 'home' | 'attendance' | 'homework' | 'results' | 'more';
type Props = { data: Dashboard; user: User; attendanceRate: number | null; navigate: (tab: AppTab) => void; refreshing?: boolean; onRefresh?: () => void };

function Header({ user }: { user: User }) {
  return <View style={styles.header}><View style={styles.avatar}><Text style={styles.avatarText}>{initials(user.name)}</Text></View><Text style={styles.brand}>Edlink</Text><Text style={styles.bell}>♢</Text></View>;
}

function LessonCard({ data }: { data: Dashboard }) {
  const lesson = data.today_timetable[0];
  return <View style={styles.lessonCard}><View><Text style={styles.kicker}>NEXT LESSON</Text><Text style={styles.lessonTitle}>{lesson?.subject ?? lesson?.label ?? 'No lesson scheduled'}</Text><Text style={styles.meta}>{lesson?.class_name ?? 'Your schedule is clear'}</Text></View><Text style={styles.lessonTime}>{lesson?.starts_at?.slice(0, 5) ?? '—'}</Text></View>;
}

export function TeacherDashboardScreen(props: Props) {
  const { data, user, navigate } = props;
  return <ScrollView style={styles.screen} contentContainerStyle={styles.content}><Header user={user} /><Text style={styles.hero}>Good Morning, {user.name}</Text><Text style={styles.school}>⌂  {user.school.name}</Text><Text style={styles.date}>{formatDate(data.date)}</Text><LessonCard data={data} /><View style={styles.actions}><Pressable style={[styles.actionCard, styles.dark]} onPress={() => navigate('attendance')}><Text style={styles.actionIcon}>✓</Text><Text style={styles.actionDarkText}>Take Attendance</Text></Pressable><Pressable style={styles.actionCard} onPress={() => navigate('homework')}><Text style={styles.actionIconDark}>▤</Text><Text style={styles.actionText}>Homework to Review</Text><View style={styles.badge}><Text style={styles.badgeText}>{data.homework.length}</Text></View></Pressable></View><Text style={styles.section}>Today’s Timetable</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.horizontal}>{data.today_timetable.map((slot, index) => <View key={slot.id} style={[styles.slot, index === 0 && styles.slotActive]}><Text style={styles.slotTime}>{slot.starts_at.slice(0, 5)}</Text><Text style={styles.slotTitle}>{slot.subject ?? slot.label ?? 'Lesson'}</Text><Text style={styles.meta}>{slot.class_name}</Text></View>)}</ScrollView></ScrollView>;
}

export function StudentDashboardScreen(props: Props) {
  const { data, user, attendanceRate, navigate } = props;
  return <ScrollView style={styles.screen} contentContainerStyle={styles.content}><Header user={user} /><Text style={styles.hero}>Hello, {firstName(user.name)}</Text><Text style={styles.school}>{data.student?.class ?? 'Your student dashboard'}</Text><Text style={styles.section}>Today’s Lessons</Text><View style={styles.whiteCard}>{data.today_timetable.slice(0, 4).map(slot => <View key={slot.id} style={styles.lessonRow}><View style={styles.subjectIcon}><Text>▣</Text></View><View style={styles.grow}><Text style={styles.rowTitle}>{slot.subject ?? slot.label ?? 'Lesson'}</Text><Text style={styles.meta}>{slot.starts_at.slice(0, 5)} – {slot.ends_at.slice(0, 5)}</Text></View></View>)}</View><Text style={styles.section}>Upcoming Homework</Text><View style={styles.whiteCard}>{data.homework.slice(0, 2).map(item => <View key={item.id} style={styles.homeworkRow}><View><Text style={styles.rowTitle}>{item.title}</Text><Text style={styles.meta}>{item.subject?.name ?? 'Assignment'}</Text></View><Text style={styles.due}>{item.due_at ? formatDate(item.due_at) : 'Upcoming'}</Text></View>)}<Pressable style={styles.goldButton} onPress={() => navigate('homework')}><Text style={styles.goldButtonText}>View Details</Text></Pressable></View><Pressable style={styles.whiteCard} onPress={() => navigate('attendance')}><Text style={styles.sectionInside}>Attendance</Text><View style={styles.rate}><Text style={styles.rateText}>{attendanceRate == null ? '—' : `${attendanceRate}%`}</Text></View><Text style={styles.centerMeta}>Your attendance record this term.</Text></Pressable></ScrollView>;
}

export function ParentDashboardScreen(props: Props) {
  const { data, user, attendanceRate, navigate } = props;
  const child = data.student;
  return <ScrollView style={styles.screen} contentContainerStyle={styles.content}><Header user={user} /><View style={styles.childCard}><View style={styles.childAvatar}><Text style={styles.avatarText}>{initials(child?.name ?? 'Student')}</Text></View><View style={styles.grow}><Text style={styles.childName}>{child?.name ?? 'Your learner'}</Text><Text style={styles.meta}>{child?.class ?? 'Student profile'}</Text></View><Text style={styles.switch}>Switch⌄</Text></View><Pressable style={styles.whiteCard} onPress={() => navigate('attendance')}><View style={styles.split}><Text style={styles.sectionInside}>▣ Attendance</Text><Text style={styles.percent}>{attendanceRate == null ? '—' : `${attendanceRate}%`}</Text></View><View style={styles.progress}><View style={[styles.progressFill, { width: `${attendanceRate ?? 0}%` }]} /></View><Text style={styles.meta}>Attendance summary for the current term.</Text></Pressable><View style={styles.actions}><Pressable style={styles.miniCard} onPress={() => navigate('results')}><Text style={styles.sectionInside}>▥ Latest Results</Text><Text style={styles.bigValue}>A</Text></Pressable><Pressable style={styles.miniCard} onPress={() => navigate('homework')}><Text style={styles.sectionInside}>▤ Homework</Text><Text style={styles.bigValue}>{data.homework.length}</Text><Text style={styles.meta}>Pending tasks</Text></Pressable></View><Text style={styles.section}>School Announcements</Text><View style={styles.whiteCard}><Text style={styles.rowTitle}>Stay connected with your school</Text><Text style={styles.meta}>Open Profile to see notices, timetable updates, and account details.</Text></View></ScrollView>;
}

const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.background }, content: { paddingBottom: 32 },
  header: { height: 72, paddingHorizontal: 20, flexDirection: 'row', alignItems: 'center', borderBottomWidth: 1, borderColor: colors.surfaceHigh }, avatar: { width: 42, height: 42, borderRadius: 21, backgroundColor: colors.surfaceHigh, alignItems: 'center', justifyContent: 'center' }, avatarText: { color: colors.navy, fontWeight: '900' }, brand: { flex: 1, marginLeft: 12, color: colors.ink, fontSize: 24, fontWeight: '800' }, bell: { fontSize: 28, color: colors.navy },
  hero: { marginHorizontal: 20, marginTop: 28, color: colors.ink, fontSize: 30, lineHeight: 37, fontWeight: '800' }, school: { marginHorizontal: 20, marginTop: 5, color: colors.muted, fontSize: 16 }, date: { marginHorizontal: 20, marginTop: 14, color: colors.ink, fontWeight: '700' },
  lessonCard: { margin: 20, padding: 18, minHeight: 126, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderRadius: radius.card, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.surfaceHigh, shadowColor: colors.navy, shadowOpacity: 0.08, shadowRadius: 12, elevation: 2 }, kicker: { color: colors.muted, fontWeight: '700', letterSpacing: 1 }, lessonTitle: { marginTop: 18, color: colors.ink, fontSize: 23, fontWeight: '800' }, lessonTime: { color: colors.ink, fontSize: 23, fontWeight: '800' }, meta: { color: colors.muted, fontSize: 14, lineHeight: 20, marginTop: 4 },
  actions: { marginHorizontal: 20, flexDirection: 'row', gap: 10 }, actionCard: { flex: 1, minHeight: 126, borderRadius: radius.card, borderWidth: 1, borderColor: colors.surfaceHigh, backgroundColor: colors.surface, alignItems: 'center', justifyContent: 'center', padding: 14 }, dark: { backgroundColor: colors.navy }, actionIcon: { color: '#FFFFFF', fontSize: 28 }, actionIconDark: { color: colors.navy, fontSize: 28 }, actionText: { color: colors.ink, fontSize: 16, fontWeight: '700', textAlign: 'center' }, actionDarkText: { color: '#FFFFFF', fontSize: 16, fontWeight: '700' }, badge: { position: 'absolute', top: 15, right: 16, width: 24, height: 24, borderRadius: 12, backgroundColor: colors.danger, alignItems: 'center', justifyContent: 'center' }, badgeText: { color: '#FFFFFF', fontWeight: '800' },
  section: { marginHorizontal: 20, marginTop: 28, marginBottom: 14, color: colors.ink, fontSize: 22, fontWeight: '800' }, horizontal: { paddingHorizontal: 20, gap: 10 }, slot: { width: 150, padding: 16, borderRadius: radius.card, backgroundColor: colors.surfaceLow }, slotActive: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.gold }, slotTime: { color: colors.goldDark, fontWeight: '700' }, slotTitle: { color: colors.ink, fontSize: 17, fontWeight: '800', marginTop: 12 },
  whiteCard: { marginHorizontal: 20, padding: 16, borderRadius: radius.card, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.surfaceHigh, shadowColor: colors.navy, shadowOpacity: 0.07, shadowRadius: 12, elevation: 2 }, lessonRow: { minHeight: 68, flexDirection: 'row', alignItems: 'center', borderBottomWidth: 1, borderColor: colors.surfaceHigh, gap: 14 }, subjectIcon: { width: 48, height: 48, borderRadius: radius.medium, backgroundColor: colors.surfaceLow, alignItems: 'center', justifyContent: 'center' }, grow: { flex: 1 }, rowTitle: { color: colors.ink, fontSize: 15, fontWeight: '700' }, homeworkRow: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 9 }, due: { color: colors.danger, fontSize: 12 }, goldButton: { marginTop: 12, minHeight: 48, borderRadius: radius.medium, backgroundColor: colors.goldDark, alignItems: 'center', justifyContent: 'center' }, goldButtonText: { color: '#FFFFFF', fontWeight: '800' }, sectionInside: { color: colors.ink, fontSize: 18, fontWeight: '800' }, rate: { alignSelf: 'center', width: 130, height: 130, marginVertical: 16, borderRadius: 65, borderWidth: 15, borderColor: colors.gold, alignItems: 'center', justifyContent: 'center' }, rateText: { color: colors.ink, fontSize: 28, fontWeight: '800' }, centerMeta: { color: colors.muted, textAlign: 'center' },
  childCard: { margin: 20, padding: 16, flexDirection: 'row', alignItems: 'center', gap: 14, borderRadius: radius.card, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.surfaceHigh }, childAvatar: { width: 58, height: 58, borderRadius: 29, backgroundColor: colors.surfaceHigh, alignItems: 'center', justifyContent: 'center' }, childName: { color: colors.ink, fontSize: 20, fontWeight: '800' }, switch: { padding: 12, borderRadius: radius.medium, backgroundColor: colors.surfaceLow, color: colors.ink, fontWeight: '700' }, split: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, percent: { color: colors.ink, fontSize: 25, fontWeight: '800' }, progress: { height: 12, marginVertical: 16, borderRadius: 6, backgroundColor: colors.surfaceHigh, overflow: 'hidden' }, progressFill: { height: '100%', borderRadius: 6, backgroundColor: colors.gold }, miniCard: { flex: 1, minHeight: 155, padding: 16, borderRadius: radius.card, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.surfaceHigh }, bigValue: { marginTop: 24, color: colors.ink, fontSize: 30, fontWeight: '800', textAlign: 'center' },
});

function firstName(name: string) { return name.trim().split(/\s+/)[0] || 'there'; }
function initials(name: string) { return name.trim().split(/\s+/).slice(0, 2).map(word => word[0]).join('').toUpperCase(); }
function formatDate(value: string) { const date = new Date(value.length === 10 ? `${value}T12:00:00` : value); return Number.isNaN(date.valueOf()) ? value : date.toLocaleDateString(undefined, { weekday: 'long', day: 'numeric', month: 'short' }); }
