import { useCallback, useEffect, useState } from 'react';
import { Alert, Image, Pressable, ScrollView, View } from 'react-native';
import * as DocumentPicker from 'expo-document-picker';
import { api } from '../../api';
import { Text, TextInput } from '../../components/Typography';
import { NativeSelect } from '../../components/NativeSelect';
import { colors } from '../../theme/index';
export function NativeStudentProfile({ token, id, onBack }: { token: string; id: number; onBack: () => void }) {
  const [fields, setFields] = useState<Record<string, string>>({}); const [editable, setEditable] = useState(false); const [photo, setPhoto] = useState<string>(); const [upload, setUpload] = useState<DocumentPicker.DocumentPickerAsset>(); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const load = useCallback(async () => { setBusy(true); setError(''); try { const response = await api.get<{ student: Record<string, string | null>; photo_url?: string; can_edit: boolean }>(`/teacher/students/${id}`, token); setFields(Object.fromEntries(Object.entries(response.data.student).map(([key, value]) => [key, value ?? '']))); setPhoto(response.data.photo_url); setEditable(response.data.can_edit); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to load learner.'); } finally { setBusy(false); } }, [token, id]);
  useEffect(() => { void load(); }, [load]);
  const save = async () => { if (busy) return; setBusy(true); try { const body = new FormData(); Object.entries(fields).forEach(([key,value]) => body.append(key,value)); if (upload) body.append('photo', { uri: upload.uri, name: upload.name, type: upload.mimeType ?? 'image/jpeg' } as unknown as Blob); await api.upload(`/teacher/students/${id}`, token, body); setUpload(undefined); await load(); Alert.alert('Profile saved'); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to save learner.'); } finally { setBusy(false); } };
  return <ScrollView contentContainerStyle={{ padding: 20, gap: 16, paddingBottom: 40 }} keyboardShouldPersistTaps="handled"><Pressable onPress={onBack}><Text style={{ color: colors.primary, paddingVertical: 12 }}>← Student directory</Text></Pressable><Text style={{ color: colors.primary, fontSize: 26, fontWeight: '800' }}>{fields.name ?? 'Student profile'}</Text>{!!error && <Text>{error}</Text>}{busy && <Text>Loading…</Text>}{(upload?.uri || photo) && <Image source={{ uri: upload?.uri ?? photo }} style={{ width: 100, height: 100, borderRadius: 50, alignSelf: 'center' }} />}{editable && <Pressable onPress={() => void DocumentPicker.getDocumentAsync({ type: ['image/jpeg', 'image/png', 'image/webp'], copyToCacheDirectory: true }).then(result => { if (!result.canceled) setUpload(result.assets[0]); }).catch(() => setError('Unable to choose photo.'))}><Text style={{ color: colors.primary }}>Choose learner photo</Text></Pressable>}
    {Object.entries(fields).map(([key, value]) => <View key={key} style={{ gap: 7 }}><Text style={{ fontWeight: '700', color: colors.primary }}>{key.replace(/_/g, ' ')}</Text>{editable && key === 'gender' ? <NativeSelect label="Gender" options={[{ value: 'male', label: 'Male' }, { value: 'female', label: 'Female' }]} value={value} onChange={next => setFields(old => ({ ...old, [key]: String(next) }))} /> : editable ? <TextInput accessibilityLabel={key.replace(/_/g, ' ')} value={value} onChangeText={next => setFields(old => ({ ...old, [key]: next }))} placeholder={key === 'date_of_birth' ? 'YYYY-MM-DD' : ''} style={{ backgroundColor: 'white', borderRadius: 14, padding: 14, color: colors.primary }} /> : <Text style={{ color: colors.textMuted }}>{value || '—'}</Text>}</View>)}
    {editable && <Pressable disabled={busy} onPress={() => void save()} style={{ backgroundColor: colors.primary, padding: 17, borderRadius: 15 }}><Text style={{ color: 'white', textAlign: 'center', fontWeight: '700' }}>Save profile</Text></Pressable>}<Pressable disabled={busy} onPress={() => void load()}><Text style={{ color: colors.primary }}>Refresh</Text></Pressable>
  </ScrollView>;
}
