import { ErrorScreen } from '../../components/ErrorScreen';
import { NativeRepeatFields } from '../../components/NativeRepeatFields';
import { exportNativeReport } from '../../components/NativeReportExport';
import { NativeSelect } from '../../components/NativeSelect';
import { useCallback, useEffect, useRef, useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, View } from 'react-native';
import { Text, TextInput } from '../../components/Typography';
import { api } from '../../api';
import { colors } from '../../theme/index';

type Field = { repeat?: Field[]; key: string; label: string; default?: string; hidden?: boolean; placeholder?: string; multiline?: boolean; secure?: boolean; multiple?: boolean; options?: Array<{ value: string; label: string }> };
type Form = { action: string; label: string; fields: Field[] };
type Module = { title: string; rows: Array<{ id: number | string; title: string; details: Record<string, string | number | boolean | null>; values?: Record<string, unknown> }>; forms: Form[]; filters?: Field[]; page: number; last_page: number };
export function NativeModuleScreen({ token, tool, onBack }: { token: string; tool: string; onBack: () => void }) {
  const [filters, setFilters] = useState<Record<string, string>>({});
  const [data, setData] = useState<Module>(); const [search, setSearch] = useState(''); const [values, setValues] = useState<Record<string, string | string[]>>({});
  const [editing, setEditing] = useState<Form>(); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const serial = useRef(0);
  const load = useCallback(async (page = 1) => { const id = ++serial.current; setBusy(true); setError(''); try { const response = await api.get<Module>(`/teacher/tools/${encodeURIComponent(tool)}?page=${page}&search=${encodeURIComponent(search)}${Object.entries(filters).filter(([,value]) => value !== '').map(([key,value]) => `&${key}=${encodeURIComponent(value)}`).join('')}`, token); if (id === serial.current) setData(response.data); } catch (e) { if (id === serial.current) setError(e instanceof Error ? e.message : 'Unable to load tool.'); } finally { if (id === serial.current) setBusy(false); } }, [token, tool, search, filters]);
  useEffect(() => { const timer = setTimeout(() => void load(), 250); return () => { clearTimeout(timer); serial.current++; }; }, [load]);
  const save = async () => { if (!editing || busy) return; setBusy(true); setError(''); try { await api.post(`/teacher/tools/${encodeURIComponent(tool)}`, token, { ...values, action: editing.action }); setEditing(undefined); setValues({}); await load(); Alert.alert('Saved', 'Your changes have been saved.'); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to save.'); } finally { setBusy(false); } };
  if (error && !data && !editing) return <ErrorScreen message={error} retry={() => load()} onBack={onBack} />;
  return <ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><Pressable onPress={onBack}><Text style={styles.back}>← Back</Text></Pressable><Text style={styles.title}>{data?.title ?? 'School workspace'}</Text>{!!error && <Text style={styles.error}>{error}</Text>}{busy && <Text style={styles.meta}>Loading…</Text>}
    {editing ? <><Text style={styles.heading}>{values.id || values.editingId ? 'Edit record' : editing.label}</Text>{editing.fields.filter(field => !field.hidden).map(field => <View key={field.key} style={{ gap: 8 }}><Text style={styles.heading}>{field.label}</Text>{field.repeat ? <NativeRepeatFields fields={field.repeat} value={String(values[field.key] ?? '')} onChange={value => setValues(old => ({ ...old, [field.key]: value }))} /> : field.options ? <NativeSelect label={field.label} options={field.options} value={values[field.key] ?? (field.multiple ? [] : '')} multiple={field.multiple} onChange={value => setValues(old => ({ ...old, [field.key]: value }))} /> : <TextInput accessibilityLabel={field.label} secureTextEntry={field.secure} value={typeof values[field.key] === 'string' ? values[field.key] as string : ''} onChangeText={text => setValues(old => ({ ...old, [field.key]: text }))} placeholder={field.placeholder ?? field.label} multiline={field.multiline} style={[styles.input, field.multiline && { minHeight: 110, textAlignVertical: 'top' }]} />}</View>)}<Pressable disabled={busy} onPress={() => Alert.alert(editing.label, 'Apply these changes to your school records?', [{ text: 'Cancel', style: 'cancel' }, { text: 'Confirm', onPress: () => void save() }])} style={styles.button}><Text style={styles.buttonText}>{editing.label}</Text></Pressable><Pressable disabled={busy} onPress={() => { setEditing(undefined); setValues({}); }}><Text style={styles.back}>Cancel</Text></Pressable></> : <>
      {data?.filters?.map(field => <View key={field.key} style={{ gap: 8 }}><Text style={styles.heading}>{field.label}</Text><NativeSelect label={field.label} options={field.options ?? []} value={filters[field.key] ?? field.default ?? ''} onChange={value => setFilters(old => ({ ...old, [field.key]: String(value), ...(field.key === 'termId' ? { studentId: '', examId: '' } : field.key === 'studentId' ? { examId: '' } : {}) }))} /></View>)}
      {data?.forms.map(form => <Pressable disabled={busy || !!error} key={form.action} onPress={() => { setValues(Object.fromEntries(form.fields.filter(field => field.default !== undefined).map(field => [field.key, field.default!]))); setEditing(form); }} style={styles.button}><Text style={styles.buttonText}>{form.label}</Text></Pressable>)}
      <TextInput accessibilityLabel="Search records" value={search} onChangeText={setSearch} placeholder="Search records" style={styles.input} />
      {data?.rows.map(row => <View key={row.id} style={styles.card}><Text style={styles.heading}>{row.title}</Text>{Object.entries(row.details).filter(([,value]) => value !== null && value !== '').map(([label, value]) => <View key={label} style={styles.detail}><Text style={styles.meta}>{label}</Text><Text style={styles.detailValue}>{typeof value === 'boolean' ? value ? 'Yes' : 'No' : String(value)}</Text></View>)}{row.values && data.forms[0] && <Pressable disabled={busy || !!error} onPress={() => { setValues(Object.fromEntries(Object.entries(row.values!).map(([key, value]) => [key, Array.isArray(value) ? value.map(String) : value == null ? '' : String(value)]))); setEditing(data.forms[0]); }}><Text style={styles.back}>Edit</Text></Pressable>}</View>)}
      {!busy && !error && !data?.rows.length && <Text style={styles.meta}>No records to show.</Text>}
      {data && data.last_page > 1 && <View style={styles.detail}><Pressable disabled={busy || data.page <= 1} onPress={() => void load(data.page - 1)}><Text style={styles.back}>Previous</Text></Pressable><Text style={styles.meta}>{data.page} / {data.last_page}</Text><Pressable disabled={busy || data.page >= data.last_page} onPress={() => void load(data.page + 1)}><Text style={styles.back}>Next</Text></Pressable></View>}
      {!!data?.rows.length && <Pressable disabled={busy} onPress={() => { setBusy(true); void exportNativeReport(data.title, data.rows).catch(() => setError('Unable to export records.')).finally(() => setBusy(false)); }}><Text style={styles.back}>Export displayed records as PDF</Text></Pressable>}
      <Pressable disabled={busy} onPress={() => void load(data?.page ?? 1)}><Text style={styles.back}>Refresh</Text></Pressable>
    </>}
  </ScrollView>;
}
const styles = StyleSheet.create({ content: { padding: 20, gap: 16, paddingBottom: 40 }, back: { color: colors.primary, fontWeight: '700', paddingVertical: 12 }, title: { color: colors.primary, fontSize: 27, fontWeight: '800' }, heading: { color: colors.primary, fontSize: 15, fontWeight: '700' }, meta: { color: colors.textMuted, fontSize: 12 }, error: { color: '#B42318', lineHeight: 21 }, card: { backgroundColor: 'white', padding: 18, borderRadius: 18, gap: 12 }, detail: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: 15 }, detailValue: { flex: 1, textAlign: 'right', color: colors.primary, fontSize: 12 }, input: { backgroundColor: 'white', padding: 15, borderRadius: 14, color: colors.primary, borderWidth: 1, borderColor: '#DEE4EF' }, button: { backgroundColor: colors.primary, padding: 17, borderRadius: 15, alignItems: 'center' }, buttonText: { color: 'white', fontWeight: '700' }, options: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 }, option: { borderRadius: 12, backgroundColor: 'white', padding: 12 }, active: { backgroundColor: colors.primary } });
