import { Text, TextInput } from '../../components/Typography';
import { Ionicons } from '@expo/vector-icons';
import { useCallback, useEffect, useState } from 'react';
import { Alert, Pressable, RefreshControl, ScrollView, StyleSheet, View } from 'react-native';
import { api, ApiError } from '../../api';
import { PageIntro } from '../../components/PageIntro';
import { colors, radius, shadows } from '../../theme/index';

type Notice = { id: number; title?: string; subject?: string; message?: string; body?: string; sent_at?: string };

export function NotificationsScreen({ token, onBack }: { token: string; onBack: () => void }) {
  const [items, setItems] = useState<Notice[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = useCallback(async () => { setLoading(true); try { const response = await api.get<{ data: Notice[] }>('/announcements', token); setItems(response.data.data ?? []); setError(''); } catch (reason) { setError(message(reason)); } finally { setLoading(false); } }, [token]);
  useEffect(() => { void load(); }, [load]);
  return <ScrollView contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={loading} onRefresh={load} tintColor={colors.primary} />}><Back onPress={onBack} /><PageIntro title="Notifications" description="School notices and updates for your account." />{error ? <Empty text={error} /> : items.map(item => <View key={item.id} style={[styles.card, shadows.card]}><View style={styles.icon}><Ionicons name="notifications-outline" size={20} color={colors.primary} /></View><View style={styles.grow}><Text style={styles.cardTitle}>{item.title ?? item.subject ?? 'School update'}</Text><Text style={styles.body}>{item.message ?? item.body ?? ''}</Text></View></View>)}{!loading && !error && !items.length && <Empty text="You’re all caught up." />}</ScrollView>;
}

export function LeaveRequestScreen({ token, onBack }: { token: string; onBack: () => void }) {
  const [type, setType] = useState('Sick leave'); const [startsOn, setStartsOn] = useState(''); const [endsOn, setEndsOn] = useState(''); const [reason, setReason] = useState(''); const [saving, setSaving] = useState(false);
  const submit = async () => { setSaving(true); try { await api.post('/leave-requests', token, { type, starts_on: startsOn, ends_on: endsOn, reason }); Alert.alert('Request submitted', 'Your leave request is pending approval.'); setStartsOn(''); setEndsOn(''); setReason(''); } catch (error) { Alert.alert('Could not submit request', message(error)); } finally { setSaving(false); } };
  return <ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><Back onPress={onBack} /><PageIntro title="Request leave" description="Send a leave request to your school administration for approval." /><Field label="Leave type" value={type} onChangeText={setType} placeholder="Sick leave" /><Field label="Start date" value={startsOn} onChangeText={setStartsOn} placeholder="YYYY-MM-DD" /><Field label="End date" value={endsOn} onChangeText={setEndsOn} placeholder="YYYY-MM-DD" /><Field label="Reason" value={reason} onChangeText={setReason} placeholder="Explain your request" multiline /><Pressable disabled={saving} onPress={() => void submit()} style={({ pressed }) => [styles.primaryButton, (pressed || saving) && styles.pressed]}><Ionicons name="send-outline" size={19} color={colors.primary} /><Text style={styles.primaryText}>{saving ? 'Submitting…' : 'Submit request'}</Text></Pressable></ScrollView>;
}

export function TeacherToolPlaceholder({ title, description, icon, onBack }: { title: string; description: string; icon: React.ComponentProps<typeof Ionicons>['name']; onBack: () => void }) {
  return <ScrollView contentContainerStyle={styles.content}><Back onPress={onBack} /><PageIntro title={title} description={description} /><View style={[styles.placeholder, shadows.card]}><View style={styles.largeIcon}><Ionicons name={icon} size={32} color={colors.primary} /></View><Text style={styles.placeholderTitle}>{title}</Text><Text style={styles.placeholderText}>This teacher screen is connected to navigation and ready for the next implementation pass.</Text></View></ScrollView>;
}

function Back({ onPress }: { onPress: () => void }) { return <Pressable onPress={onPress} style={styles.back}><Ionicons name="arrow-back" size={20} color={colors.primary} /><Text style={styles.backText}>Home</Text></Pressable>; }
function Field(props: { label: string; value: string; onChangeText: (value: string) => void; placeholder: string; multiline?: boolean }) { return <View><Text style={styles.label}>{props.label}</Text><TextInput {...props} style={[styles.input, props.multiline && styles.multiline]} placeholderTextColor={colors.textMuted} /></View>; }
function Empty({ text }: { text: string }) { return <View style={styles.placeholder}><Ionicons name="notifications-off-outline" size={27} color={colors.textMuted} /><Text style={styles.placeholderText}>{text}</Text></View>; }
function message(error: unknown) { return error instanceof ApiError ? error.message : 'Check your connection and try again.'; }

const styles = StyleSheet.create({
  content: { padding: 20, paddingBottom: 40, gap: 12 }, back: { alignSelf: 'flex-start', minHeight: 42, flexDirection: 'row', alignItems: 'center', gap: 7, paddingHorizontal: 13, borderRadius: radius.full, backgroundColor: colors.secondary }, backText: { color: colors.primary, fontWeight: '900' }, card: { minHeight: 92, flexDirection: 'row', alignItems: 'flex-start', gap: 12, padding: 15, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: radius.md }, icon: { width: 40, height: 40, borderRadius: 13, backgroundColor: colors.secondary, alignItems: 'center', justifyContent: 'center' }, grow: { flex: 1 }, cardTitle: { color: colors.textDark, fontSize: 15, fontWeight: '900' }, body: { color: colors.textMuted, fontSize: 12, lineHeight: 18, marginTop: 5 }, label: { color: colors.textDark, fontSize: 12, fontWeight: '800', marginBottom: 7 }, input: { minHeight: 52, borderRadius: radius.md, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, color: colors.textDark, paddingHorizontal: 14 }, multiline: { minHeight: 110, paddingTop: 14, textAlignVertical: 'top' }, primaryButton: { minHeight: 54, borderRadius: radius.md, backgroundColor: colors.secondary, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8 }, primaryText: { color: colors.primary, fontSize: 14, fontWeight: '900' }, pressed: { opacity: 0.62 }, placeholder: { minHeight: 190, borderRadius: radius.md, backgroundColor: colors.surface, alignItems: 'center', justifyContent: 'center', padding: 24, borderWidth: 1, borderColor: colors.border }, largeIcon: { width: 64, height: 64, borderRadius: 20, backgroundColor: colors.secondary, alignItems: 'center', justifyContent: 'center' }, placeholderTitle: { color: colors.textDark, fontSize: 20, fontWeight: '900', marginTop: 14 }, placeholderText: { color: colors.textMuted, textAlign: 'center', lineHeight: 20, marginTop: 7 },
});
