import * as SecureStore from 'expo-secure-store';
import { Ionicons } from '@expo/vector-icons';
import { StatusBar } from 'expo-status-bar';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Alert, Platform, Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaProvider, SafeAreaView } from 'react-native-safe-area-context';
import { api, ApiError } from './src/api';
import { AuthFlow } from './src/screens/auth/AuthFlow';
import type { Assignment, AttendanceRecord, AttendanceRow, AttendanceStatus, Dashboard, ExamResult, Student, User } from './src/types';
import { colors, radius } from './src/theme';
import { ParentDashboardScreen, StudentDashboardScreen, TeacherDashboardScreen, type AppTab } from './src/screens/app/DashboardScreens';
import { BottomTabBar } from './src/components/Navigation';
import { ProfileScreen } from './src/screens/app/ProfileScreen';
import { BrandLogo } from './src/components/BrandLogo';
import { PageIntro as ScreenHeader } from './src/components/PageIntro';
import { PaymentsScreen } from './src/screens/app/PaymentsScreen';
import { LeaveRequestScreen, NotificationsScreen, TeacherToolPlaceholder } from './src/screens/app/TeacherToolsScreens';

const TOKEN_KEY = 'edlink.mobile.token';
const STATUSES: AttendanceStatus[] = ['present', 'absent', 'late', 'excused'];
type Tab = AppTab;

export default function App() {
  const [session, setSession] = useState<{ token: string; user: User }>();
  const [booting, setBooting] = useState(true);
  useEffect(() => { void (async () => {
    const token = await SecureStore.getItemAsync(TOKEN_KEY);
    if (token) try { setSession({ token, user: (await api.me(token)).data }); } catch { await SecureStore.deleteItemAsync(TOKEN_KEY); }
    setBooting(false);
  })(); }, []);
  const signIn = async (school_number: string, email: string, password: string, expectedRole: User['role']) => {
    const { data } = await api.login({ school_number, email, password, device_name: `${Platform.OS} Edlink app` });
    if (data.user.role !== expectedRole) { await api.logout(data.token).catch(() => undefined); throw new ApiError(`These credentials belong to a ${data.user.role} account. Choose the correct role and try again.`, 403); }
    await SecureStore.setItemAsync(TOKEN_KEY, data.token); setSession(data);
  };
  const signOut = async () => { if (session) await api.logout(session.token).catch(() => undefined); await SecureStore.deleteItemAsync(TOKEN_KEY); setSession(undefined); };
  return (
    <SafeAreaProvider>
      {booting ? <LoadingScreen /> : !session ? <AuthFlow onSignIn={signIn} messageFor={messageFor} /> : <AuthenticatedApp {...session} onSignOut={signOut} />}
    </SafeAreaProvider>
  );
}

function AuthenticatedApp({ token, user, onSignOut }: { token: string; user: User; onSignOut: () => Promise<void> }) {
  const tabs: Tab[] = user.role === 'teacher' ? ['home', 'attendance', 'homework', 'more'] : ['home', 'attendance', 'results', 'homework', 'payments', 'more'];
  const [tab, setTab] = useState<Tab>('home'); const [activeRoot, setActiveRoot] = useState<Tab>('home'); const [children, setChildren] = useState<Student[]>([]); const [studentId, setStudentId] = useState<number>();
  useEffect(() => { if (tabs.includes(tab)) setActiveRoot(tab); }, [tab]);
  useEffect(() => { if (user.role === 'parent') void api.get<Student[]>('/children', token).then(({ data }) => { setChildren(data); setStudentId(data[0]?.id); }).catch(error => Alert.alert('Children unavailable', messageFor(error))); }, [token, user.role]);
  return <SafeAreaView style={styles.safe}><StatusBar style="dark" />
    {user.role === 'parent' && children.length > 0 && <ChildPicker children={children} selected={studentId} onSelect={setStudentId} />}
    <View style={styles.screen}>
      {tab === 'home' && <Home token={token} user={user} studentId={studentId} navigate={setTab} onSignOut={onSignOut} />}
      {tab === 'attendance' && <Attendance token={token} user={user} studentId={studentId} />}
      {tab === 'homework' && <Homework token={token} user={user} studentId={studentId} isParent={user.role === 'parent'} />}
      {tab === 'results' && <Results token={token} user={user} studentId={studentId} isParent={user.role === 'parent'} />}
      {tab === 'payments' && <PaymentsScreen token={token} studentId={studentId} isParent={user.role === 'parent'} />}
      {tab === 'more' && <ProfileScreen token={token} user={user} studentId={studentId} onSignOut={onSignOut} navigate={setTab} />}
      {tab === 'notifications' && <NotificationsScreen token={token} onBack={() => setTab('home')} />}
      {user.role === 'teacher' && tab === 'leave' && <LeaveRequestScreen token={token} onBack={() => setTab('home')} />}
      {user.role === 'teacher' && tab === 'add_marks' && <TeacherToolPlaceholder title="Add marks" description="Select an assigned exam paper and enter learner marks." icon="create-outline" onBack={() => setTab('home')} />}
      {user.role === 'teacher' && tab === 'view_marks' && <TeacherToolPlaceholder title="View marks" description="Review marks for your assigned classes and subjects." icon="reader-outline" onBack={() => setTab('home')} />}
      {user.role === 'teacher' && tab === 'teacher_results' && <TeacherToolPlaceholder title="Results" description="Review published results for learners within your academic scope." icon="trophy-outline" onBack={() => setTab('home')} />}
      {user.role === 'teacher' && tab === 'add_homework' && <TeacherToolPlaceholder title="Add homework" description="Create and publish homework for an assigned class and subject." icon="add-circle-outline" onBack={() => setTab('home')} />}
      {user.role === 'teacher' && tab === 'homework' && <Pressable accessibilityRole="button" accessibilityLabel="Add homework" onPress={() => setTab('add_homework')} style={styles.floatingAdd}><Ionicons name="add" size={30} color={colors.gold} /></Pressable>}
    </View>
    <BottomTabBar tabs={tabs} activeTab={activeRoot} onSelect={setTab} />
  </SafeAreaView>;
}

function Home({ token, user, studentId, navigate, onSignOut }: { token: string; user: User; studentId?: number; navigate: (tab: Tab) => void; onSignOut: () => Promise<void> }) {
  const [data, setData] = useState<Dashboard>(); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = useCallback(async () => { if (user.role === 'parent' && !studentId) { setLoading(false); return; } setLoading(true); try { setData((await api.get<Dashboard>(`/dashboard${studentId ? `?student_id=${studentId}` : ''}`, token)).data); setError(''); } catch (e) { setError(messageFor(e)); } finally { setLoading(false); } }, [studentId, token, user.role]);
  useEffect(() => { void load(); }, [load]);
  if (loading && !data) return <InlineLoading />; if (error && !data) return <ErrorState message={error} retry={load} />; if (!data) return <Empty message="Choose a learner to view their dashboard." />;
  const total = Object.values(data.attendance).reduce((sum, value) => sum + Number(value), 0); const rate = total ? Math.round(Number(data.attendance.present ?? 0) / total * 100) : null;
  const props = { data, user: { ...user, onSignOut, navigate, nextLesson: data.next_lesson }, attendanceRate: rate, navigate, refreshing: loading, onRefresh: load };
  if (user.role === 'teacher') return <TeacherDashboardScreen {...props} />;
  if (user.role === 'parent') return <ParentDashboardScreen {...props} />;
  return <StudentDashboardScreen {...props} />;
}

function Attendance({ token, user, studentId }: { token: string; user: User; studentId?: number }) { return user.role === 'teacher' ? <TeacherAttendance token={token} user={user} /> : <AttendanceHistory token={token} user={user} studentId={studentId} isParent={user.role === 'parent'} />; }

function AttendanceHistory({ token, user, studentId, isParent }: { token: string; user: User; studentId?: number; isParent: boolean }) {
  const [records, setRecords] = useState<AttendanceRecord[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = useCallback(async () => { if (isParent && !studentId) { setLoading(false); return; } setLoading(true); try { const response = await api.get<{ data: AttendanceRecord[] }>(`/attendance${studentId ? `?student_id=${studentId}` : ''}`, token); setRecords(response.data.data ?? []); setError(''); } catch (e) { setError(messageFor(e)); } finally { setLoading(false); } }, [isParent, studentId, token]);
  useEffect(() => { void load(); }, [load]); const counts = useMemo(() => Object.fromEntries(STATUSES.map(status => [status, records.filter(item => item.status === status).length])), [records]);
  if (loading && !records.length) return <InlineLoading />; if (error && !records.length) return <ErrorState message={error} retry={load} />;
  return <ScrollView contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={loading} onRefresh={load} />}><ScreenHeader title="Attendance" subtitle="Recent school attendance records" user={user} /><View style={styles.statsRow}>{STATUSES.slice(0, 3).map(status => <Stat key={status} label={capitalize(status)} value={`${counts[status]}`} />)}</View>{records.map(record => <View key={record.id} style={styles.rowCard}><View><Text style={styles.cardTitle}>{formatDate(record.attendance_date)}</Text><Text style={styles.cardMeta}>{record.session_key || 'Daily attendance'}</Text></View><Pill status={record.status} /></View>)}{!records.length && <Empty message="No attendance records yet." />}</ScrollView>;
}

function TeacherAttendance({ token, user }: { token: string; user: User }) {
  const [assignments, setAssignments] = useState<Assignment[]>([]); const [selected, setSelected] = useState<Assignment>(); const [rows, setRows] = useState<AttendanceRow[]>([]); const [version, setVersion] = useState<string>(); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const date = new Date().toISOString().slice(0, 10);
  useEffect(() => { void api.get<Assignment[]>('/teaching-assignments', token).then(({ data }) => { setAssignments(data); setSelected(data[0]); }).catch(error => Alert.alert('Assignments unavailable', messageFor(error))).finally(() => setLoading(false)); }, [token]);
  useEffect(() => { if (!selected) return; setLoading(true); const subjectQuery = selected.subject_id ? `&subject_id=${selected.subject_id}` : ''; const query = `?school_class_id=${selected.school_class_id}${subjectQuery}&attendance_date=${date}&session_key=${attendanceSession(selected)}`; void api.get<AttendanceRow[]>(`/attendance${query}`, token).then(response => { setRows(response.data); setVersion(response.meta?.version as string | undefined); }).catch(error => Alert.alert('Register unavailable', messageFor(error))).finally(() => setLoading(false)); }, [date, selected, token]);
  const cycle = (id: number) => setRows(current => current.map(row => row.student.id === id ? { ...row, status: STATUSES[(STATUSES.indexOf(row.status) + 1) % STATUSES.length] } : row));
  const save = async () => { if (!selected) return; setSaving(true); try { const response = await api.post<{ saved: number; version: string }>('/attendance', token, { school_class_id: selected.school_class_id, subject_id: selected.subject_id, attendance_date: date, session_key: attendanceSession(selected), base_version: version, records: rows.map(row => ({ student_id: row.student.id, status: row.status })) }); setVersion(response.data.version); Alert.alert('Attendance saved', `${response.data.saved} learner records were saved.`); } catch (error) { Alert.alert(error instanceof ApiError && error.status === 409 ? 'Register changed' : 'Could not save', messageFor(error)); } finally { setSaving(false); } };
  if (loading && !assignments.length) return <InlineLoading />;
  return <ScrollView contentContainerStyle={styles.content}><ScreenHeader title="Take attendance" subtitle={`${formatDate(date)} · Tap a status to change it`} user={user} /><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.chipRow}>{assignments.map(item => { const active = item.school_class_id === selected?.school_class_id && item.subject_id === selected?.subject_id; return <Pressable key={`${item.school_class_id}-${item.subject_id}`} onPress={() => setSelected(item)} style={[styles.chip, active && styles.chipActive]}><Text style={[styles.chipText, active && styles.chipTextActive]}>{item.class_name} • {item.subject_name}</Text></Pressable>; })}</ScrollView>{!assignments.length && <Empty message="No teaching assignments are available for the current term." />}{rows.map(row => <View key={row.student.id} style={styles.rowCard}><View style={styles.grow}><Text style={styles.cardTitle}>{row.student.name}</Text><Text style={styles.cardMeta}>{row.student.admission_no}</Text></View><Pressable onPress={() => cycle(row.student.id)}><Pill status={row.status} /></Pressable></View>)}{!!rows.length && <PrimaryButton label={saving ? 'Saving…' : `Save ${rows.length} records`} onPress={save} disabled={saving} />}</ScrollView>;
}

function Results({ token, studentId, isParent }: { token: string; user?: User; studentId?: number; isParent: boolean }) {
  const [results, setResults] = useState<ExamResult[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = useCallback(async () => { if (isParent && !studentId) { setLoading(false); return; } setLoading(true); try { setResults((await api.get<ExamResult[]>(`/results${studentId ? `?student_id=${studentId}` : ''}`, token)).data); setError(''); } catch (e) { setError(messageFor(e)); } finally { setLoading(false); } }, [isParent, studentId, token]); useEffect(() => { void load(); }, [load]);
  if (loading && !results.length) return <InlineLoading />; if (error && !results.length) return <ErrorState message={error} retry={load} />;
  return <ScrollView contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={loading} onRefresh={load} />}><ScreenHeader title="Academic results" subtitle="Track published marks, subject scores, and overall academic performance." icon="trophy-outline" /><View style={styles.termRow}><View style={styles.termChip}><Text style={styles.termChipText}>{results[0]?.term ?? 'Current Term'}  ⌄</Text></View></View>{results.map(exam => <View key={exam.id} style={styles.resultCard}><View style={styles.resultHeader}><Text style={styles.examTitle}>{exam.name}</Text><View style={styles.averageChip}><Text style={styles.averageChipText}>Overall Average</Text></View></View><Text style={styles.resultAverage}>{average(exam)}<Text style={styles.percentSign}>%</Text></Text>{exam.papers.map(paper => <View key={paper.id} style={styles.markRow}><View style={styles.resultSubjectIcon}><Text style={styles.resultSubjectIconText}>▣</Text></View><Text style={styles.markSubject}>{paper.subject ?? 'Subject'}</Text><Text style={styles.markScore}>{paper.score ?? '—'}/{paper.maximum_score}</Text></View>)}</View>)}{!results.length && <Empty message="No published results are available yet." />}</ScrollView>;
}

type HomeworkItem = { id: number; title: string; description?: string | null; due_at?: string | null; subject?: { name: string } | null };
function Homework({ token, studentId, isParent }: { token: string; user?: User; studentId?: number; isParent: boolean }) {
  const [items, setItems] = useState<HomeworkItem[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = useCallback(async () => { if (isParent && !studentId) { setLoading(false); return; } setLoading(true); try { const response = await api.get<{ data: HomeworkItem[] }>(`/homework${studentId ? `?student_id=${studentId}` : ''}`, token); setItems(response.data.data ?? []); setError(''); } catch (e) { setError(messageFor(e)); } finally { setLoading(false); } }, [isParent, studentId, token]);
  useEffect(() => { void load(); }, [load]); if (loading && !items.length) return <InlineLoading />; if (error && !items.length) return <ErrorState message={error} retry={load} />;
  return <ScrollView contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={loading} onRefresh={load} tintColor="#231E34" />}><ScreenHeader title="Homework" subtitle="See assigned work, due dates, submissions, and teacher reviews in one place." icon="book-outline" /><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.filterRow}>{['Upcoming', 'Submitted', 'Reviewed'].map((label, index) => <View key={label} style={[styles.filterChip, index === 0 && styles.filterChipActive]}><Text style={[styles.filterText, index === 0 && styles.filterTextActive]}>{label}</Text></View>)}</ScrollView>{items.map(item => <View key={item.id} style={styles.homeworkCard}><View style={styles.homeworkAccent} /><View style={styles.homeworkTop}><View style={styles.subjectTag}><Text style={styles.subjectTagText}>{item.subject?.name ?? 'General'}</Text></View>{item.due_at && <View style={styles.dueChip}><Text style={styles.dueChipText}>◷  Due {formatDate(item.due_at)}</Text></View>}</View><Text style={styles.homeworkCardTitle}>{item.title}</Text>{!!item.description && <Text numberOfLines={2} style={styles.homeworkDescription}>{item.description}</Text>}</View>)}{!items.length && <Empty message="No homework has been posted yet." />}</ScrollView>;
}

function FigmaPageHeader({ title, subtitle }: { title: string; subtitle: string }) { return <View style={styles.figmaPageHeader}><View style={styles.smallBrand}><Text style={styles.smallBrandText}>✎</Text></View><View><Text style={styles.pageTitle}>{title}</Text><Text style={styles.pageLead}>{subtitle}</Text></View></View>; }

function attendanceSession(assignment: Assignment) { return assignment.attendance_type === 'daily' ? 'daily' : `subject:${assignment.subject_id}`; }

function PrimaryButton({ label, onPress, disabled }: { label: string; onPress: () => void; disabled?: boolean }) { return <Pressable onPress={onPress} disabled={disabled} style={({ pressed }) => [styles.primaryButton, (pressed || disabled) && styles.buttonMuted]}><Text style={styles.primaryButtonText}>{label}</Text></Pressable>; }
function ChildPicker({ children, selected, onSelect }: { children: Student[]; selected?: number; onSelect: (id: number) => void }) { return <ScrollView horizontal showsHorizontalScrollIndicator={false} style={styles.childPicker} contentContainerStyle={styles.chipRow}>{children.map(child => <Pressable key={child.id} onPress={() => onSelect(child.id)} style={[styles.chip, child.id === selected && styles.chipActive]}><Text style={[styles.chipText, child.id === selected && styles.chipTextActive]}>{child.name}</Text></Pressable>)}</ScrollView>; }
function Stat({ label, value }: { label: string; value: string }) { return <View style={styles.stat}><Text style={styles.statValue}>{value}</Text><Text style={styles.statLabel}>{label}</Text></View>; } function Pill({ status }: { status: AttendanceStatus }) { return <View style={[styles.pill, styles[`status_${status}`]]}><Text style={styles.pillText}>{capitalize(status)}</Text></View>; } function Section({ title }: { title: string }) { return <Text style={styles.sectionTitle}>{title}</Text>; }
function InlineLoading() { return <View style={styles.center}><ActivityIndicator color="#176B5B" size="large" /><Text style={styles.muted}>Loading Edlink…</Text></View>; } function LoadingScreen() { return <SafeAreaView style={[styles.safe, styles.center]}><BrandLogo /><ActivityIndicator color="#176B5B" /></SafeAreaView>; } function Empty({ message, compact }: { message: string; compact?: boolean }) { return <View style={[styles.empty, compact && styles.emptyCompact]}><Text style={styles.emptyText}>{message}</Text></View>; } function ErrorState({ message, retry }: { message: string; retry: () => void }) { return <View style={styles.center}><Text style={styles.errorTitle}>We couldn’t load this</Text><Text style={styles.muted}>{message}</Text><PrimaryButton label="Try again" onPress={retry} /></View>; }
function messageFor(error: unknown) { return error instanceof ApiError ? error.message : 'Cannot reach the Edlink server. Check your connection.'; } function firstName(name: string) { return name.trim().split(/\s+/)[0] || 'there'; } function initials(name: string) { return name.trim().split(/\s+/).slice(0, 2).map(word => word[0]).join('').toUpperCase(); } function capitalize(value: string) { return value.charAt(0).toUpperCase() + value.slice(1); } function shortTime(value: string) { return value?.slice(0, 5) ?? ''; } function formatDate(value: string) { const date = new Date(value.length === 10 ? `${value}T12:00:00` : value); return Number.isNaN(date.valueOf()) ? value : date.toLocaleDateString(undefined, { weekday: 'short', day: 'numeric', month: 'short' }); } function average(exam: ExamResult) { const papers = exam.papers.filter(paper => paper.score != null && paper.maximum_score > 0); return papers.length ? Math.round(papers.reduce((sum, paper) => sum + Number(paper.score) / paper.maximum_score * 100, 0) / papers.length) : 0; }

const styles = StyleSheet.create({
  floatingAdd: { position: 'absolute', right: 22, bottom: 20, width: 58, height: 58, borderRadius: 29, backgroundColor: colors.navy, alignItems: 'center', justifyContent: 'center', elevation: 8 },
  termRow: { flexDirection: 'row', justifyContent: 'flex-end', marginTop: 14, marginBottom: 4 },
  flex: { flex: 1 }, safe: { flex: 1, backgroundColor: colors.background }, screen: { flex: 1, backgroundColor: colors.background }, center: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 16, padding: 28 }, muted: { color: colors.muted, textAlign: 'center', lineHeight: 21 },
  figmaAuthWrap: { flexGrow: 1, padding: 0 }, splashScreen: { minHeight: '100%', alignItems: 'center', justifyContent: 'center', overflow: 'hidden' }, roleScreen: { minHeight: '100%', alignItems: 'center', paddingTop: 55, overflow: 'hidden' }, yellowCurve: { position: 'absolute', top: -145, width: 540, height: 300, borderRadius: 270, backgroundColor: '#FFCC33' }, navyFooter: { position: 'absolute', bottom: -115, width: 480, height: 190, borderRadius: 240, backgroundColor: '#231E34', alignItems: 'center', paddingTop: 28 }, copyright: { color: 'white', fontSize: 10 }, brandLockup: { alignItems: 'center' }, brandMark: { width: 78, height: 78, borderRadius: 39, borderWidth: 5, borderColor: '#231E34', backgroundColor: '#FFCC33', alignItems: 'center', justifyContent: 'center' }, brandMarkLarge: { width: 130, height: 130, borderRadius: 65, borderWidth: 7 }, brandPencil: { color: '#231E34', fontSize: 48, fontWeight: '900' }, brandPencilLarge: { fontSize: 78 }, brandName: { color: '#231E34', fontSize: 30, fontWeight: '900', marginTop: 8 }, brandNameLarge: { fontSize: 42 }, roleTitle: { color: '#231E34', fontSize: 18, fontWeight: '800', marginTop: 42, marginBottom: 28 }, roleGrid: { width: 285, flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'center', gap: 30 }, roleOption: { width: 95, alignItems: 'center', gap: 9 }, roleIcon: { width: 82, height: 82, borderRadius: 12, backgroundColor: '#231E34', alignItems: 'center', justifyContent: 'center' }, roleIconText: { color: 'white', fontSize: 40, fontWeight: '900' }, roleLabel: { color: '#231E34', fontSize: 14 },
  loginWrap: { flexGrow: 1, justifyContent: 'center', padding: 24 }, welcomeWrap: { justifyContent: 'space-between', paddingTop: 82, paddingBottom: 50 }, logo: { width: 62, height: 62, borderRadius: 31, backgroundColor: '#FFCC33', borderWidth: 4, borderColor: '#231E34', alignItems: 'center', justifyContent: 'center', marginBottom: 22 }, logoText: { color: '#231E34', fontSize: 35, fontWeight: '900' }, welcomeCopy: { marginTop: 'auto', marginBottom: 'auto' }, welcomeEyebrow: { color: '#231E34', fontSize: 12, fontWeight: '900', letterSpacing: 1.8, marginBottom: 14 }, welcomeTitle: { color: '#231E34', fontSize: 42, lineHeight: 48, fontWeight: '900', maxWidth: 330 }, welcomeLead: { color: '#777381', fontSize: 17, lineHeight: 26, marginTop: 18, maxWidth: 340 }, welcomeActions: { gap: 15 }, welcomeFootnote: { color: '#8D8993', fontSize: 12, textAlign: 'center' }, loginTopRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 34 }, backButton: { width: 44, height: 44, borderRadius: 15, backgroundColor: '#F7E9EC', alignItems: 'center', justifyContent: 'center' }, backButtonText: { color: '#231E34', fontSize: 33, lineHeight: 35 }, stepDots: { flexDirection: 'row', gap: 7 }, stepDot: { width: 24, height: 5, borderRadius: 3, backgroundColor: '#E8DDE0' }, stepDotActive: { backgroundColor: '#DE3B55' }, loginTitle: { fontSize: 30, fontWeight: '800', color: '#231E34' }, loginLead: { color: '#777381', fontSize: 16, marginTop: 7, marginBottom: 26 }, loginCard: { backgroundColor: 'white', borderRadius: 24, padding: 20, gap: 16, shadowColor: '#231E34', shadowOpacity: 0.1, shadowRadius: 20, elevation: 3 }, schoolBadge: { flexDirection: 'row', alignItems: 'center', gap: 12, backgroundColor: '#F9E9EC', borderRadius: 18, padding: 13, marginBottom: 14 }, schoolBadgeIcon: { width: 42, height: 42, borderRadius: 13, backgroundColor: '#231E34', alignItems: 'center', justifyContent: 'center' }, schoolBadgeIconText: { color: 'white', fontSize: 20, fontWeight: '900' }, schoolBadgeLabel: { color: '#777381', fontSize: 10, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 0.7 }, schoolBadgeValue: { color: '#231E34', fontSize: 14, fontWeight: '900', marginTop: 2 }, schoolBadgeAction: { color: '#DE3B55', fontSize: 12, fontWeight: '800' }, field: { gap: 7 }, label: { color: '#231E34', fontSize: 13, fontWeight: '700' }, input: { height: 52, borderBottomWidth: 2, borderColor: '#B8B4BD', paddingHorizontal: 4, color: '#231E34', fontSize: 16, backgroundColor: 'white' }, error: { color: '#DE3B55', lineHeight: 20 }, serverHint: { color: '#9B97A0', fontSize: 11, textAlign: 'center', marginTop: 20 }, primaryButton: { minHeight: 52, borderRadius: 9, backgroundColor: '#231E34', alignItems: 'center', justifyContent: 'center', paddingHorizontal: 20, marginTop: 4 }, primaryButtonText: { color: 'white', fontWeight: '800', fontSize: 15 }, buttonMuted: { opacity: 0.62 },
  appHeader: { paddingHorizontal: 20, paddingTop: 12, paddingBottom: 14, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, eyebrow: { color: '#71807B', fontSize: 11, textTransform: 'uppercase', letterSpacing: 1.1, fontWeight: '700' }, headerName: { color: '#17352F', fontSize: 22, fontWeight: '800', marginTop: 3 }, avatar: { width: 43, height: 43, borderRadius: 15, backgroundColor: '#DCEBE5', alignItems: 'center', justifyContent: 'center' }, avatarText: { color: '#176B5B', fontWeight: '900' }, childPicker: { flexGrow: 0, borderTopWidth: 1, borderBottomWidth: 1, borderColor: '#E3E9E5' }, chipRow: { paddingHorizontal: 20, paddingVertical: 10, gap: 8 }, chip: { paddingVertical: 9, paddingHorizontal: 14, borderRadius: 99, backgroundColor: '#E8EEEB' }, chipActive: { backgroundColor: '#176B5B' }, chipText: { color: '#52635D', fontSize: 12, fontWeight: '700' }, chipTextActive: { color: 'white' },
  content: { padding: 20, paddingBottom: 34, gap: 12 }, figmaContent: { paddingBottom: 34, gap: 12 }, dashboardHeader: { height: 170, alignItems: 'center', overflow: 'hidden' }, coralArc: { position: 'absolute', top: -190, width: 560, height: 330, borderRadius: 280, backgroundColor: '#DE3B55' }, profileCircle: { position: 'absolute', bottom: 5, width: 104, height: 104, borderRadius: 52, borderWidth: 5, borderColor: '#DE3B55', backgroundColor: 'white', alignItems: 'center', justifyContent: 'center' }, profileInitials: { color: '#231E34', fontSize: 27, fontWeight: '900' }, welcomePanel: { marginHorizontal: 20, backgroundColor: '#231E34', borderRadius: 12, padding: 16 }, welcomePanelTitle: { color: 'white', fontSize: 16, fontWeight: '800' }, welcomePanelText: { color: '#E9E7ED', fontSize: 11, lineHeight: 17, marginTop: 5 }, dashboardSection: { marginHorizontal: 20, marginTop: 8, color: '#231E34', fontSize: 12, fontWeight: '900' }, featureGrid: { paddingHorizontal: 20, flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', rowGap: 14 }, featureTile: { width: '31%', minHeight: 104, borderRadius: 14, alignItems: 'center', justifyContent: 'center', padding: 8 }, tileMint: { backgroundColor: '#E7F7F5' }, tilePink: { backgroundColor: '#F9E9EC' }, featureIcon: { color: '#1556C0', fontSize: 31, fontWeight: '900' }, featureLabel: { color: '#231E34', fontSize: 11, marginTop: 8, textAlign: 'center' }, heroCard: { backgroundColor: '#231E34', borderRadius: 16, padding: 22, minHeight: 150, justifyContent: 'flex-end' }, heroKicker: { color: '#FFCC33', textTransform: 'uppercase', fontSize: 11, fontWeight: '800', letterSpacing: 1.2 }, heroTitle: { color: 'white', fontSize: 24, fontWeight: '800', marginTop: 8 }, heroMeta: { color: '#E9E7ED', marginTop: 6 }, statsRow: { flexDirection: 'row', gap: 9, marginVertical: 2, paddingHorizontal: 20 }, stat: { flex: 1, padding: 14, minHeight: 91, backgroundColor: 'white', borderRadius: 14, justifyContent: 'space-between', borderWidth: 1, borderColor: '#EEEAF0' }, statValue: { color: '#DE3B55', fontWeight: '900', fontSize: 23 }, statLabel: { color: '#777381', fontSize: 11, fontWeight: '600' }, pageTitle: { fontSize: 26, color: '#231E34', fontWeight: '900' }, pageLead: { color: '#777381', marginBottom: 5 }, sectionTitle: { color: '#231E34', fontSize: 17, fontWeight: '800', marginTop: 13 },
  listCard: { backgroundColor: 'white', borderRadius: 18, padding: 14, flexDirection: 'row', alignItems: 'center', gap: 13, borderWidth: 1, borderColor: '#E6ECE8' }, timeBadge: { width: 58, height: 49, borderRadius: 13, backgroundColor: '#E7F2ED', alignItems: 'center', justifyContent: 'center' }, timeText: { color: '#176B5B', fontWeight: '900' }, grow: { flex: 1 }, cardTitle: { color: '#263E38', fontWeight: '800', fontSize: 15 }, cardMeta: { color: '#73817D', fontSize: 12, marginTop: 4 }, simpleCard: { backgroundColor: 'white', padding: 16, borderRadius: 17, borderWidth: 1, borderColor: '#E6ECE8' }, rowCard: { backgroundColor: 'white', padding: 15, borderRadius: 17, borderWidth: 1, borderColor: '#E6ECE8', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
  pill: { borderRadius: 99, paddingVertical: 8, paddingHorizontal: 12 }, status_present: { backgroundColor: '#DDF2E7' }, status_absent: { backgroundColor: '#F8DEDD' }, status_late: { backgroundColor: '#F7EBCB' }, status_excused: { backgroundColor: '#DEE8F5' }, pillText: { color: '#344C45', fontSize: 11, fontWeight: '800' },
  resultsTitleRow: { flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between', marginBottom: 18 }, resultsTitle: { color: '#151C27', fontSize: 34, lineHeight: 39, fontWeight: '900' }, termChip: { minHeight: 48, paddingHorizontal: 16, borderRadius: 12, borderWidth: 1, borderColor: '#C9C5CD', backgroundColor: '#F0F3FF', justifyContent: 'center' }, termChipText: { color: '#151C27', fontSize: 14 }, resultCard: { backgroundColor: 'white', padding: 17, borderRadius: 16, borderWidth: 1, borderColor: '#D9E1F1', gap: 10, shadowColor: '#211D35', shadowOpacity: 0.08, shadowRadius: 14, elevation: 2 }, resultHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingBottom: 8 }, examTitle: { color: '#151C27', fontSize: 24, fontWeight: '900', flexShrink: 1 }, averageChip: { backgroundColor: '#FFF3D5', borderRadius: 99, paddingVertical: 7, paddingHorizontal: 12 }, averageChipText: { color: '#765A00', fontSize: 11 }, resultAverage: { color: '#09051C', fontSize: 50, fontWeight: '900', marginVertical: 8 }, percentSign: { fontSize: 24, color: '#48464D' }, markRow: { minHeight: 58, flexDirection: 'row', alignItems: 'center', borderTopWidth: 1, borderColor: '#DCE2F3', paddingTop: 10, gap: 12 }, resultSubjectIcon: { width: 42, height: 42, borderRadius: 10, backgroundColor: '#F0F3FF', alignItems: 'center', justifyContent: 'center' }, resultSubjectIconText: { color: '#09051C', fontSize: 21, fontWeight: '900' }, markSubject: { color: '#151C27', fontSize: 16, flex: 1 }, markScore: { color: '#09051C', fontSize: 16, fontWeight: '900' },
  homeworkTitle: { color: '#151C27', fontSize: 34, fontWeight: '900', marginBottom: 16 }, filterRow: { gap: 10, paddingBottom: 18 }, filterChip: { minHeight: 46, paddingHorizontal: 20, borderRadius: 99, borderWidth: 1, borderColor: '#C9C5CD', backgroundColor: '#F0F3FF', justifyContent: 'center' }, filterChipActive: { backgroundColor: '#765A00', borderColor: '#765A00' }, filterText: { color: '#48464D', fontSize: 14, fontWeight: '700' }, filterTextActive: { color: 'white' }, homeworkCard: { minHeight: 150, backgroundColor: 'white', padding: 20, borderRadius: 16, borderWidth: 1, borderColor: '#D9E1F1', overflow: 'hidden', shadowColor: '#211D35', shadowOpacity: 0.06, shadowRadius: 12, elevation: 2 }, homeworkAccent: { position: 'absolute', left: 0, top: 0, bottom: 0, width: 5, backgroundColor: '#FFCE4B' }, homeworkTop: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10 }, subjectTag: { paddingVertical: 6, paddingHorizontal: 10, borderRadius: 8, backgroundColor: '#E2E8F8' }, subjectTagText: { color: '#48464D', fontWeight: '600' }, dueChip: { paddingVertical: 7, paddingHorizontal: 11, borderRadius: 99, backgroundColor: '#FFCE4B', maxWidth: '55%' }, dueChipText: { color: '#765A00', fontSize: 11, fontWeight: '800' }, homeworkCardTitle: { color: '#151C27', fontSize: 22, lineHeight: 29, fontWeight: '800', marginTop: 16 }, homeworkDescription: { color: '#48464D', fontSize: 14, lineHeight: 20, marginTop: 8 },
  empty: { minHeight: 150, alignItems: 'center', justifyContent: 'center', backgroundColor: '#F0F3FF', borderRadius: 18, padding: 20 }, emptyCompact: { minHeight: 86 }, emptyText: { color: '#777381', textAlign: 'center' }, errorTitle: { color: '#231E34', fontSize: 20, fontWeight: '800' }, figmaListCard: { backgroundColor: 'white', padding: 15, borderRadius: 16, borderWidth: 1, borderColor: '#E2E8F8', flexDirection: 'row', gap: 13 }, subjectBadge: { width: 48, height: 48, borderRadius: 12, backgroundColor: '#F0F3FF', alignItems: 'center', justifyContent: 'center' }, subjectBadgeText: { color: '#765A00', fontWeight: '900', fontSize: 23 }, descriptionText: { color: '#777381', fontSize: 12, lineHeight: 18, marginTop: 7 }, figmaPageHeader: { flexDirection: 'row', alignItems: 'center', gap: 13, marginBottom: 8 }, smallBrand: { width: 48, height: 48, borderRadius: 16, backgroundColor: '#211D35', alignItems: 'center', justifyContent: 'center' }, smallBrandText: { color: 'white', fontSize: 25, fontWeight: '900' }, profileCard: { flexDirection: 'row', alignItems: 'center', gap: 14, backgroundColor: '#211D35', padding: 18, borderRadius: 16 }, profileAvatar: { width: 62, height: 62, borderRadius: 31, backgroundColor: '#FFCE4B', alignItems: 'center', justifyContent: 'center' }, profileName: { color: 'white', fontSize: 17, fontWeight: '900' }, profileMeta: { color: '#D5D1DB', fontSize: 12, marginTop: 4 }, noticeCard: { backgroundColor: '#FFF9E8', padding: 16, borderRadius: 14 }, miniClass: { color: '#765A00', fontSize: 11, fontWeight: '800' }, outlineButton: { minHeight: 50, borderWidth: 2, borderColor: '#765A00', borderRadius: 16, alignItems: 'center', justifyContent: 'center', marginTop: 10 }, outlineButtonText: { color: '#765A00', fontWeight: '900' }, tabBar: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#F9F9FF', borderTopWidth: 1, borderColor: '#E2E8F8', paddingHorizontal: 10, paddingBottom: Platform.OS === 'android' ? 8 : 0, paddingTop: 8 }, tab: { flex: 1, minHeight: 52, alignItems: 'center', justifyContent: 'center', gap: 2, paddingVertical: 4, borderRadius: 999 }, tabSelected: { backgroundColor: '#FFCE4B' }, tabIcon: { fontSize: 19, color: '#48464D', fontWeight: '800' }, tabLabel: { fontSize: 9, color: '#48464D', fontWeight: '700' }, tabActive: { color: '#765A00' },
});
