import { useState } from 'react';
import { FlatList, Modal, Pressable, StyleSheet, View } from 'react-native';
import { Text, TextInput } from './Typography';
import { colors } from '../theme/index';
export function NativeSelect({ label, options, value, multiple = false, onChange }: { label: string; options: Array<{ value: string; label: string }>; value: string | string[]; multiple?: boolean; onChange: (value: string | string[]) => void }) {
  const [open, setOpen] = useState(false); const [search, setSearch] = useState('');
  const selected = Array.isArray(value) ? value : [value];
  const names = options.filter(option => selected.includes(option.value)).map(option => option.label);
  return <><Pressable accessibilityRole="button" accessibilityLabel={label} onPress={() => { setSearch(''); setOpen(true); }} style={styles.input}><Text style={styles.text}>{names.length ? names.length > 2 ? `${names.length} selected` : names.join(', ') : `Choose ${label.toLowerCase()}`}</Text></Pressable><Modal visible={open} onRequestClose={() => setOpen(false)} animationType="slide"><View style={styles.sheet}><View style={styles.header}><Text style={styles.title}>{label}</Text><Pressable onPress={() => setOpen(false)}><Text style={styles.done}>Done</Text></Pressable></View><TextInput accessibilityLabel={`Search ${label}`} value={search} onChangeText={setSearch} placeholder="Search options" style={styles.input} /><FlatList data={options.filter(option => option.label.toLowerCase().includes(search.toLowerCase()))} keyExtractor={item => item.value} keyboardShouldPersistTaps="handled" ListEmptyComponent={<Text>No matching options.</Text>} renderItem={({ item }) => <Pressable accessibilityRole="checkbox" accessibilityState={{ checked: selected.includes(item.value) }} onPress={() => { onChange(multiple ? selected.includes(item.value) ? selected.filter(v => v !== item.value) : [...selected, item.value] : item.value); if (!multiple) setOpen(false); }} style={styles.row}><Text style={styles.text}>{item.label}</Text><Text style={styles.done}>{selected.includes(item.value) ? '✓' : ''}</Text></Pressable>} /></View></Modal></>;
}
const styles = StyleSheet.create({ input: { borderWidth: 1, borderColor: '#DDE4EF', borderRadius: 14, backgroundColor: 'white', padding: 15, color: colors.primary }, text: { color: colors.primary, flexShrink: 1 }, sheet: { flex: 1, padding: 22, paddingTop: 55, gap: 16, backgroundColor: colors.background }, header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 16 }, title: { color: colors.primary, fontSize: 22, fontWeight: '700', flex: 1 }, done: { color: colors.primary, fontWeight: '700', padding: 9 }, row: { minHeight: 58, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12, borderBottomWidth: 1, borderColor: '#E2E7F0' } });
