@extends('layouts.platform-auth')
@section('title','Platform sign in')
@section('content')
<div class="rounded-3xl border border-slate-200 bg-white p-7 shadow-xl shadow-slate-200/60 sm:p-9"><div class="flex items-start justify-between gap-4"><div><p class="text-xs font-bold uppercase tracking-[.18em] text-yellow-600">Platform access</p><h2 class="mt-2 text-2xl font-extrabold">Welcome back</h2><p class="mt-2 text-sm leading-6 text-slate-500">Sign in with your Edlink platform administrator account.</p></div><span class="flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl bg-slate-100 text-slate-600"><svg class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.8" d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z"/></svg></span></div>
<form method="POST" action="{{ route('platform.login.store') }}" class="mt-8 space-y-5">@csrf
<label class="block"><span class="text-xs font-bold text-slate-700">Email address</span><input name="email" value="{{ old('email') }}" type="email" autocomplete="username" autofocus required class="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm outline-none transition focus:border-yellow-400 focus:bg-white focus:ring-4 focus:ring-yellow-400/10" placeholder="owner@edlink.com"></label>
<label class="block"><span class="text-xs font-bold text-slate-700">Password</span><input name="password" type="password" autocomplete="current-password" required class="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm outline-none transition focus:border-yellow-400 focus:bg-white focus:ring-4 focus:ring-yellow-400/10" placeholder="Enter your password"></label>
@if($errors->any())<div class="rounded-xl border border-rose-200 bg-rose-50 p-3 text-xs font-medium text-rose-700">{{ $errors->first() }}</div>@endif
<button class="flex w-full items-center justify-center gap-2 rounded-xl bg-slate-950 px-5 py-3.5 text-sm font-bold text-white transition hover:bg-slate-800 focus:ring-4 focus:ring-yellow-400/30">Continue securely <span aria-hidden="true">→</span></button>
</form><div class="mt-6 flex items-center gap-2 text-xs text-slate-400"><svg class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.8" d="M9 12l2 2 4-4m6-2a9 9 0 11-18 0 9 9 0 0118 0z"/></svg>Password verification is followed by MFA.</div></div>
<p class="mt-5 text-center text-xs text-slate-400">Looking for your school account? <a href="{{ route('login') }}" class="font-bold text-slate-700 hover:text-yellow-600">School login</a></p>
@endsection