import { Ionicons } from '@expo/vector-icons';
import { useState } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { colors, radius } from '../../theme';
import type { Role, SchoolIdentity } from '../../types';
import { AuthLayout } from './AuthLayout';

export function LoginScreen({ role, school, email, password, error, busy, biometricAvailable, onEmailChange, onPasswordChange, onChangeSchool, onChangeRole, onForgotPassword, onBiometricSignIn, onSubmit }: { role: Role; school: SchoolIdentity; email: string; password: string; error: string; busy: boolean; biometricAvailable: boolean; onEmailChange: (value: string) => void; onPasswordChange: (value: string) => void; onChangeSchool: () => void; onChangeRole: () => void; onForgotPassword: () => void; onBiometricSignIn: () => void; onSubmit: () => void }) {
  const [showPassword, setShowPassword] = useState(false); const roleLabel = role === 'parent' ? 'Parent or guardian' : `${role.charAt(0).toUpperCase()}${role.slice(1)}`;
  return <AuthLayout eyebrow="Welcome back" school={school}>
    <View style={styles.headingRow}><Pressable accessibilityLabel="Change school" onPress={onChangeSchool} style={styles.back}><Ionicons name="chevron-back" size={23} color={colors.navy} /></Pressable><Pressable onPress={onChangeRole} style={styles.role}><Ionicons name="person-circle-outline" size={20} color={colors.navy} /><Text style={styles.roleText}>{roleLabel}</Text><Ionicons name="chevron-down" size={15} color={colors.navy} /></Pressable></View>
    <Text style={styles.title}>Log in</Text><Text style={styles.lead}>Use the account details registered at {school.name}.</Text>
    <Text style={styles.label}>Email address</Text><View style={[styles.field, !!error && styles.fieldError]}><Ionicons name="mail-outline" size={21} color={colors.navy} /><TextInput value={email} onChangeText={onEmailChange} placeholder="you@school.com" placeholderTextColor="#85838B" keyboardType="email-address" autoCapitalize="none" autoComplete="email" style={styles.input} /></View>
    <Text style={styles.label}>Password</Text><View style={[styles.field, !!error && styles.fieldError]}><Ionicons name="lock-closed-outline" size={21} color={colors.navy} /><TextInput value={password} onChangeText={onPasswordChange} placeholder="Enter your password" placeholderTextColor="#85838B" secureTextEntry={!showPassword} autoCapitalize="none" autoComplete="password" returnKeyType="done" onSubmitEditing={onSubmit} style={styles.input} /><Pressable accessibilityLabel={showPassword ? 'Hide password' : 'Show password'} onPress={() => setShowPassword(value => !value)} hitSlop={10}><Ionicons name={showPassword ? 'eye-off-outline' : 'eye-outline'} size={21} color={colors.navy} /></Pressable></View>
    <Pressable onPress={onForgotPassword} style={styles.forgot}><Text style={styles.forgotText}>Forgot password?</Text></Pressable>
    {!!error && <View style={styles.errorRow}><Ionicons name="alert-circle" size={16} color={colors.danger} /><Text style={styles.error}>{error}</Text></View>}
    <Pressable disabled={busy} onPress={onSubmit} style={({ pressed }) => [styles.button, (busy || pressed) && styles.buttonMuted]}>{busy ? <ActivityIndicator color={colors.gold} /> : <><Text style={styles.buttonText}>Log in to Edlink</Text><Ionicons name="arrow-forward-circle" size={23} color={colors.gold} /></>}</Pressable>
    {biometricAvailable && <Pressable onPress={onBiometricSignIn} style={styles.biometric}><Ionicons name="finger-print" size={25} color={colors.navy} /><Text style={styles.biometricText}>Unlock with device biometrics</Text></Pressable>}
  </AuthLayout>;
}

const styles = StyleSheet.create({
  headingRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, back: { width: 44, height: 44, borderRadius: 22, borderWidth: 2, borderColor: colors.navy, alignItems: 'center', justifyContent: 'center' }, role: { minHeight: 42, borderRadius: 21, paddingHorizontal: 13, backgroundColor: colors.surfaceLow, borderWidth: 1, borderColor: colors.navy, flexDirection: 'row', alignItems: 'center', gap: 7 }, roleText: { color: colors.navy, fontSize: 12, fontWeight: '900' }, title: { color: colors.navy, fontSize: 31, fontWeight: '900', marginTop: 18 }, lead: { color: colors.muted, fontSize: 14, lineHeight: 20, marginTop: 4 }, label: { color: colors.ink, fontSize: 13, fontWeight: '800', marginTop: 18, marginBottom: 7 }, field: { minHeight: 56, borderRadius: radius.card, borderWidth: 2, borderColor: colors.navy, paddingHorizontal: 14, flexDirection: 'row', alignItems: 'center', gap: 10 }, fieldError: { borderColor: colors.danger }, input: { flex: 1, height: 54, color: colors.ink, fontSize: 15 }, forgot: { alignSelf: 'flex-end', minHeight: 40, justifyContent: 'center' }, forgotText: { color: colors.goldDark, fontSize: 13, fontWeight: '900' }, errorRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 6 }, error: { flex: 1, color: colors.danger, fontSize: 12, lineHeight: 17 }, button: { minHeight: 58, marginTop: 15, borderRadius: radius.card, backgroundColor: colors.navy, flexDirection: 'row', gap: 10, justifyContent: 'center', alignItems: 'center' }, buttonText: { color: '#FFFFFF', fontWeight: '900', fontSize: 16 }, buttonMuted: { opacity: 0.65 }, biometric: { minHeight: 52, marginTop: 13, borderRadius: radius.card, borderWidth: 2, borderColor: colors.navy, flexDirection: 'row', gap: 9, alignItems: 'center', justifyContent: 'center' }, biometricText: { color: colors.navy, fontSize: 13, fontWeight: '900' },
});
