import { Text, TextInput } from '../../components/Typography';
import { Ionicons } from '@expo/vector-icons';
import { useState } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, View } from 'react-native';
import { colors, radius } from '../../theme';
import type { SchoolIdentity } from '../../types';
import { AuthLayout } from './AuthLayout';

export function PasswordRecoveryScreen({ school, initialEmail, error, busy, onBack, onRequest, onReset }: { school: SchoolIdentity; initialEmail: string; error: string; busy: boolean; onBack: () => void; onRequest: (email: string) => Promise<boolean>; onReset: (values: { email: string; token: string; password: string; password_confirmation: string }) => Promise<boolean> }) {
  const [mode, setMode] = useState<'request' | 'sent' | 'reset'>('request'); const [email, setEmail] = useState(initialEmail); const [token, setToken] = useState(''); const [password, setPassword] = useState(''); const [confirmation, setConfirmation] = useState('');
  const request = async () => { if (await onRequest(email)) setMode('sent'); };
  const reset = async () => { await onReset({ email, token, password, password_confirmation: confirmation }); };
  return <AuthLayout eyebrow="Account recovery" school={school}>
    <Pressable accessibilityLabel="Back to login" onPress={onBack} style={styles.back}><Ionicons name="chevron-back" size={23} color={colors.navy} /></Pressable>
    {mode === 'request' && <><Text style={styles.title}>Reset your password</Text><Text style={styles.lead}>Enter the email registered at {school.name}. We’ll send a secure reset link.</Text><Field icon="mail-outline" placeholder="you@school.com" value={email} onChangeText={setEmail} keyboardType="email-address" autoCapitalize="none" /><Error message={error} /><Action busy={busy} label="Send reset link" icon="paper-plane" onPress={() => void request()} /></>}
    {mode === 'sent' && <View style={styles.sentWrap}><View style={styles.sentIcon}><Ionicons name="mail-open-outline" size={35} color={colors.gold} /></View><Text style={styles.title}>Check your email</Text><Text style={styles.lead}>If those details match an Edlink account, a reset link has been sent. Open it to choose a new password.</Text><Pressable onPress={() => setMode('reset')} style={styles.outlineButton}><Text style={styles.outlineText}>I have a reset token</Text></Pressable><Pressable onPress={() => setMode('request')} style={styles.textButton}><Text style={styles.textButtonLabel}>Send again</Text></Pressable></View>}
    {mode === 'reset' && <><Text style={styles.title}>Choose a new password</Text><Text style={styles.lead}>Paste the secure token from your reset email, then create a password with at least 8 characters.</Text><Field icon="key-outline" placeholder="Reset token" value={token} onChangeText={setToken} autoCapitalize="none" /><Field icon="lock-closed-outline" placeholder="New password" value={password} onChangeText={setPassword} secureTextEntry /><Field icon="checkmark-circle-outline" placeholder="Confirm new password" value={confirmation} onChangeText={setConfirmation} secureTextEntry /><Error message={error} /><Action busy={busy} label="Set new password" icon="shield-checkmark" onPress={() => void reset()} /></>}
  </AuthLayout>;
}

function Field(props: React.ComponentProps<typeof TextInput> & { icon: React.ComponentProps<typeof Ionicons>['name'] }) { const { icon, ...input } = props; return <View style={styles.field}><Ionicons name={icon} size={21} color={colors.navy} /><TextInput {...input} placeholderTextColor="#85838B" style={styles.input} /></View>; }
function Error({ message }: { message: string }) { return message ? <View style={styles.errorRow}><Ionicons name="alert-circle" size={16} color={colors.danger} /><Text style={styles.error}>{message}</Text></View> : null; }
function Action({ busy, label, icon, onPress }: { busy: boolean; label: string; icon: React.ComponentProps<typeof Ionicons>['name']; onPress: () => void }) { return <Pressable disabled={busy} onPress={onPress} style={[styles.button, busy && styles.muted]}>{busy ? <ActivityIndicator color={colors.gold} /> : <><Text style={styles.buttonText}>{label}</Text><Ionicons name={icon} size={21} color={colors.gold} /></>}</Pressable>; }
const styles = StyleSheet.create({ back: { width: 44, height: 44, borderRadius: 22, borderWidth: 2, borderColor: colors.navy, alignItems: 'center', justifyContent: 'center' }, title: { color: colors.navy, fontSize: 29, lineHeight: 35, fontWeight: '900', marginTop: 20 }, lead: { color: colors.muted, fontSize: 14, lineHeight: 21, marginTop: 7, marginBottom: 10 }, field: { minHeight: 56, borderRadius: radius.card, borderWidth: 2, borderColor: colors.navy, paddingHorizontal: 14, marginTop: 13, flexDirection: 'row', alignItems: 'center', gap: 10 }, input: { flex: 1, height: 54, color: colors.ink, fontSize: 14 }, errorRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 6, marginTop: 10 }, error: { flex: 1, color: colors.danger, fontSize: 12, lineHeight: 17 }, button: { minHeight: 58, borderRadius: radius.card, backgroundColor: colors.navy, marginTop: 22, flexDirection: 'row', gap: 9, alignItems: 'center', justifyContent: 'center' }, buttonText: { color: '#FFFFFF', fontWeight: '900', fontSize: 16 }, muted: { opacity: 0.6 }, sentWrap: { alignItems: 'center' }, sentIcon: { width: 72, height: 72, borderRadius: 36, backgroundColor: colors.navy, alignItems: 'center', justifyContent: 'center', borderWidth: 3, borderColor: colors.gold }, outlineButton: { width: '100%', minHeight: 54, borderRadius: radius.card, borderWidth: 2, borderColor: colors.navy, justifyContent: 'center', alignItems: 'center', marginTop: 28 }, outlineText: { color: colors.navy, fontWeight: '900' }, textButton: { minHeight: 48, justifyContent: 'center' }, textButtonLabel: { color: colors.goldDark, fontWeight: '900' } });
