import { Ionicons } from '@expo/vector-icons';
import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { colors, radius } from '../../theme';
import { AuthLayout } from './AuthLayout';

export function SchoolScreen({ school, error, busy, onChange, onBack, onContinue }: { school: string; error: string; busy: boolean; onChange: (value: string) => void; onBack: () => void; onContinue: () => void }) {
  return <AuthLayout eyebrow="Your school, your space">
    <View style={styles.headingRow}><Pressable accessibilityLabel="Go back" onPress={onBack} style={styles.back}><Ionicons name="chevron-back" size={23} color={colors.navy} /></Pressable><View style={styles.step}><View style={[styles.dot, styles.dotActive]} /><View style={styles.dot} /><View style={styles.dot} /></View></View>
    <Text style={styles.title}>Find your school</Text><Text style={styles.lead}>Enter the school number provided by your administrator. We’ll securely load your school’s identity.</Text>
    <Text style={styles.label}>School number</Text><View style={[styles.field, !!error && styles.fieldError]}><Ionicons name="school-outline" size={21} color={colors.navy} /><TextInput value={school} onChangeText={value => onChange(value.toUpperCase())} placeholder="e.g. EDL-4K9P2" placeholderTextColor="#85838B" autoCapitalize="characters" autoCorrect={false} returnKeyType="go" onSubmitEditing={onContinue} style={styles.input} />{school ? <Pressable onPress={() => onChange('')} hitSlop={10}><Ionicons name="close-circle" size={20} color={colors.muted} /></Pressable> : null}</View>
    {!!error && <View style={styles.errorRow}><Ionicons name="alert-circle" size={16} color={colors.danger} /><Text style={styles.error}>{error}</Text></View>}
    <Pressable disabled={busy} onPress={onContinue} style={({ pressed }) => [styles.button, (busy || pressed) && styles.buttonMuted]}>{busy ? <ActivityIndicator color={colors.gold} /> : <><Text style={styles.buttonText}>Continue</Text><Ionicons name="arrow-forward-circle" size={23} color={colors.gold} /></>}</Pressable>
    <View style={styles.tip}><Ionicons name="shield-checkmark-outline" size={20} color={colors.navy} /><Text style={styles.tipText}>Your school number only identifies the school. Your account details remain private.</Text></View>
  </AuthLayout>;
}

const styles = StyleSheet.create({
  headingRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, back: { width: 44, height: 44, borderRadius: 22, borderWidth: 2, borderColor: colors.navy, alignItems: 'center', justifyContent: 'center' }, step: { flexDirection: 'row', gap: 6 }, dot: { width: 22, height: 6, borderRadius: 3, backgroundColor: colors.surfaceHigh }, dotActive: { backgroundColor: colors.gold }, title: { color: colors.navy, fontSize: 30, fontWeight: '900', letterSpacing: -0.6, marginTop: 24 }, lead: { color: colors.muted, fontSize: 14, lineHeight: 21, marginTop: 8 }, label: { color: colors.ink, fontSize: 13, fontWeight: '800', marginTop: 26, marginBottom: 8 }, field: { minHeight: 58, borderRadius: radius.card, borderWidth: 2, borderColor: colors.navy, backgroundColor: colors.surface, paddingHorizontal: 15, flexDirection: 'row', alignItems: 'center', gap: 11 }, fieldError: { borderColor: colors.danger }, input: { flex: 1, height: 56, color: colors.ink, fontSize: 16, fontWeight: '700', letterSpacing: 0.5 }, errorRow: { flexDirection: 'row', gap: 6, marginTop: 8, alignItems: 'flex-start' }, error: { flex: 1, color: colors.danger, fontSize: 12, lineHeight: 17 }, button: { minHeight: 58, marginTop: 26, borderRadius: radius.card, backgroundColor: colors.navy, flexDirection: 'row', gap: 10, alignItems: 'center', justifyContent: 'center' }, buttonText: { color: '#FFFFFF', fontSize: 16, fontWeight: '900' }, buttonMuted: { opacity: 0.65 }, tip: { flexDirection: 'row', gap: 10, marginTop: 20, padding: 14, borderRadius: radius.card, backgroundColor: colors.surfaceLow, borderWidth: 1, borderColor: colors.navy }, tipText: { flex: 1, color: colors.muted, fontSize: 12, lineHeight: 18 },
});
