@extends('layouts.platform', ['title' => $group->name])

@section('content')
<div class="space-y-6">
    <a href="{{ route('platform.groups.index') }}" class="inline-flex items-center gap-2 text-xs font-bold text-slate-500 hover:text-amber-700">← Back to school groups</a>
    @if(session('status'))<div class="rounded-2xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-bold text-emerald-800">{{ session('status') }}</div>@endif
    @if($errors->any())<div class="rounded-2xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm font-bold text-rose-800">{{ $errors->first() }}</div>@endif

    <section class="relative overflow-hidden rounded-2xl bg-gradient-to-r from-slate-900 via-slate-800 to-slate-900 p-6 text-white shadow-sm sm:p-8">
        <div class="relative z-10 flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><span class="inline-flex rounded-full border border-amber-400/20 bg-amber-400/10 px-3 py-1 font-mono text-[10px] font-black uppercase tracking-wider text-amber-300">{{ $group->code }}</span><h1 class="mt-4 text-2xl font-black tracking-tight text-amber-300 sm:text-3xl">{{ $group->name }}</h1><p class="mt-1.5 text-sm font-medium text-slate-400">Manage branch membership, staff access, and consolidated group reporting.</p></div><div class="flex gap-3"><div class="rounded-xl border border-slate-700 bg-slate-800/60 px-4 py-3"><span class="block text-[9px] font-black uppercase tracking-wider text-slate-400">Branches</span><b class="mt-1 block text-lg text-white">{{ $group->schools->count() }}</b></div><div class="rounded-xl border border-slate-700 bg-slate-800/60 px-4 py-3"><span class="block text-[9px] font-black uppercase tracking-wider text-slate-400">Assignments</span><b class="mt-1 block text-lg text-white">{{ $assignments->count() }}</b></div></div></div>
        <div class="pointer-events-none absolute -bottom-20 -right-12 h-64 w-64 rounded-full bg-amber-500/10 blur-3xl"></div>
    </section>

    <div class="grid items-start gap-6 xl:grid-cols-2">
        <section class="rounded-2xl border border-slate-200/80 bg-white shadow-xs">
            <div class="border-b border-slate-100 p-5"><h2 class="text-base font-black text-slate-900">Group branches</h2><p class="mt-1 text-xs text-slate-500">Each tenant keeps independent data and licensing.</p></div>
            <div class="divide-y divide-slate-100 px-5">@forelse($group->schools as $school)<a href="{{ route('platform.schools.show', $school) }}" class="flex items-center justify-between gap-4 py-4"><div class="flex min-w-0 items-center gap-3"><span class="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-amber-50 text-xs font-black text-amber-800 ring-1 ring-inset ring-amber-200">{{ strtoupper(substr($school->name, 0, 1)) }}</span><span class="min-w-0"><b class="block truncate text-sm text-slate-900">{{ $school->branch_name ?: $school->name }}</b><small class="font-mono text-slate-400">{{ $school->school_number }}</small></span></div><span class="shrink-0 text-xs font-bold text-slate-500">{{ number_format($school->students_count) }} learners</span></a>@empty<p class="py-10 text-center text-xs text-slate-400">No branches assigned.</p>@endforelse</div>
            @if($availableSchools->isNotEmpty())<form method="POST" action="{{ route('platform.groups.branches.store', $group) }}" class="grid gap-4 border-t border-slate-100 bg-slate-50/70 p-5 sm:grid-cols-2">@csrf<label><span class="text-xs font-bold text-slate-700">School</span><select name="school_id" required class="mt-2 w-full rounded-xl border-slate-200 bg-white px-3 py-3 text-xs font-semibold focus:border-amber-400 focus:ring-amber-400">@foreach($availableSchools as $school)<option value="{{ $school->id }}">{{ $school->name }}</option>@endforeach</select></label><label><span class="text-xs font-bold text-slate-700">Branch label</span><input name="branch_name" value="{{ old('branch_name') }}" placeholder="Optional" class="mt-2 w-full rounded-xl border-slate-200 bg-white px-3 py-3 text-xs font-semibold placeholder:text-slate-400 focus:border-amber-400 focus:ring-amber-400"></label><button class="rounded-xl bg-slate-900 px-4 py-3 text-xs font-black text-white hover:bg-slate-800 sm:col-span-2">Add branch to group</button></form>@endif
        </section>

        <section class="rounded-2xl border border-slate-200/80 bg-white shadow-xs">
            <div class="border-b border-slate-100 p-5"><h2 class="text-base font-black text-slate-900">Assign staff access</h2><p class="mt-1 text-xs leading-5 text-slate-500">Assign an existing staff member to a branch with a scoped role and optional designation.</p></div>
            <form method="POST" action="{{ route('platform.groups.access.store', $group) }}" class="grid gap-4 p-5 sm:grid-cols-2">@csrf
                <label class="sm:col-span-2"><span class="text-xs font-bold text-slate-700">Staff email</span><input name="email" type="email" required value="{{ old('email') }}" placeholder="staff@school.com" class="mt-2 w-full rounded-xl border-slate-200 bg-slate-50 px-4 py-3 text-sm font-semibold placeholder:text-slate-400 focus:border-amber-400 focus:bg-white focus:ring-amber-400"></label>
                <label><span class="text-xs font-bold text-slate-700">Branch</span><select name="school_id" required class="mt-2 w-full rounded-xl border-slate-200 bg-slate-50 px-3 py-3 text-xs font-semibold focus:border-amber-400 focus:bg-white focus:ring-amber-400">@foreach($group->schools as $school)<option value="{{ $school->id }}">{{ $school->branch_name ?: $school->name }}</option>@endforeach</select></label>
                <label><span class="text-xs font-bold text-slate-700">Role in branch</span><select name="role" required class="mt-2 w-full rounded-xl border-slate-200 bg-slate-50 px-3 py-3 text-xs font-semibold focus:border-amber-400 focus:bg-white focus:ring-amber-400">@foreach(['teacher'=>'Teacher','bursar'=>'Bursar','academic_admin'=>'Academic administrator','registrar'=>'Registrar','admin'=>'Administrator'] as $value=>$label)<option value="{{ $value }}">{{ $label }}</option>@endforeach</select></label>
                <label class="sm:col-span-2"><span class="text-xs font-bold text-slate-700">Designation and permissions</span><select name="designation_id" class="mt-2 w-full rounded-xl border-slate-200 bg-slate-50 px-3 py-3 text-xs font-semibold focus:border-amber-400 focus:bg-white focus:ring-amber-400"><option value="">Use role defaults / no designation</option>@foreach($designations as $designation)<option value="{{ $designation->id }}">{{ $designation->school->branch_name ?: $designation->school->name }} — {{ $designation->name }}</option>@endforeach</select><span class="mt-1.5 block text-[10px] text-slate-400">The designation must belong to the selected branch.</span></label>
                <label class="flex items-start gap-3 rounded-xl border border-slate-200 bg-slate-50 p-4 sm:col-span-2"><input type="checkbox" name="can_view_group" value="1" class="mt-0.5 rounded border-slate-300 text-amber-500 focus:ring-amber-400"><span><b class="block text-xs text-slate-800">Allow consolidated reporting</b><span class="mt-1 block text-[10px] leading-4 text-slate-400">Access All branches reports and group-level graphs.</span></span></label>
                <button class="rounded-xl bg-amber-400 px-4 py-3 text-xs font-black text-slate-950 hover:bg-amber-300 sm:col-span-2">Save branch assignment</button>
            </form>
        </section>
    </div>

    <section class="overflow-hidden rounded-2xl border border-slate-200/80 bg-white shadow-xs"><div class="border-b border-slate-100 p-5"><h2 class="text-base font-black text-slate-900">Current staff assignments</h2><p class="mt-1 text-xs text-slate-500">Roles and permissions apply only inside the listed branch.</p></div><div class="overflow-x-auto"><table class="w-full min-w-[760px] text-left text-xs"><thead class="bg-slate-50/80 text-[10px] font-black uppercase tracking-wider text-slate-500"><tr><th class="px-5 py-3">Staff</th><th class="px-5 py-3">Branch</th><th class="px-5 py-3">Role</th><th class="px-5 py-3">Designation</th><th class="px-5 py-3">Group reports</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($assignments as $assignment)<tr class="hover:bg-slate-50/70"><td class="px-5 py-4"><b class="block text-sm text-slate-900">{{ $assignment->user_name }}</b><span class="text-slate-400">{{ $assignment->email }}</span></td><td class="px-5 py-4 font-bold text-slate-700">{{ $assignment->branch_name ?: $assignment->school_name }}</td><td class="px-5 py-4 text-slate-600">{{ str($assignment->role)->replace('_', ' ')->title() }}</td><td class="px-5 py-4 text-slate-600">{{ $assignment->designation_name ?: 'Role defaults' }}</td><td class="px-5 py-4"><span class="rounded-full px-2.5 py-1 text-[10px] font-black {{ $assignment->can_view_group ? 'bg-emerald-50 text-emerald-700 ring-1 ring-inset ring-emerald-200' : 'bg-slate-100 text-slate-500' }}">{{ $assignment->can_view_group ? 'Allowed' : 'No' }}</span></td></tr>@empty<tr><td colspan="5" class="p-12 text-center text-slate-400">No staff assignments found.</td></tr>@endforelse</tbody></table></div></section>
</div>
@endsection
