<div class="mx-auto max-w-7xl space-y-6">
    <div class="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-sm font-semibold text-yellow-600">Attendance</p><h1 class="text-2xl font-bold text-slate-900">Attendance reports</h1><p class="mt-1 text-sm text-slate-500">Review daily and subject attendance{{ $term ? ' for '.$term->name.', '.$term->year : '' }}.</p></div><div class="flex gap-2"><a wire:navigate href="{{ route('attendance.index') }}" class="rounded-xl border bg-white px-4 py-2.5 text-sm font-bold">Daily register</a><button wire:click="exportCsv" class="rounded-xl bg-emerald-600 px-4 py-2.5 text-sm font-bold text-white">Export CSV</button></div></div>

    <section class="rounded-2xl border bg-white p-5 shadow-sm">
        <div class="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
            <label class="text-sm font-semibold">From date<input wire:model.live="fromDate" type="date" class="mt-1.5 w-full rounded-xl border-slate-300 text-sm focus:border-yellow-400 focus:ring-yellow-400"></label>
            <label class="text-sm font-semibold">To date<input wire:model.live="toDate" type="date" class="mt-1.5 w-full rounded-xl border-slate-300 text-sm focus:border-yellow-400 focus:ring-yellow-400"></label>
            <label class="text-sm font-semibold">Class<select wire:model.live="schoolClassId" class="mt-1.5 w-full rounded-xl border-slate-300 text-sm"><option value="">All classes</option>@foreach ($classes as $class)<option value="{{ $class->id }}">{{ $class->name }}</option>@endforeach</select></label>
            <label class="text-sm font-semibold">Stream<select wire:model.live="streamId" class="mt-1.5 w-full rounded-xl border-slate-300 text-sm"><option value="">All streams</option>@foreach ($streams as $stream)<option value="{{ $stream->id }}">{{ $stream->name }}</option>@endforeach</select></label>
            <label class="text-sm font-semibold">Subject / session<select wire:model.live="subjectId" class="mt-1.5 w-full rounded-xl border-slate-300 text-sm"><option value="all">All sessions</option><option value="daily">Daily register</option>@foreach ($subjects as $subject)<option value="{{ $subject->id }}">{{ $subject->name }}</option>@endforeach</select></label>
            <label class="text-sm font-semibold">Status<select wire:model.live="status" class="mt-1.5 w-full rounded-xl border-slate-300 text-sm"><option value="all">All statuses</option><option value="present">Present</option><option value="late">Late</option><option value="absent">Absent</option><option value="excused">Excused</option></select></label>
            <label class="text-sm font-semibold xl:col-span-2">Find learner<div class="flex gap-2"><input wire:model.live.debounce.300ms="search" placeholder="Name or admission number" class="mt-1.5 w-full rounded-xl border-slate-300 text-sm"><button type="button" wire:click="clearFilters" class="mt-1.5 rounded-xl border px-4 text-sm font-bold text-slate-600">Reset</button></div></label>
        </div>
    </section>

    <div class="grid grid-cols-2 gap-3 lg:grid-cols-5">
        <div class="rounded-2xl border bg-white p-4"><p class="text-xs font-bold text-slate-400">RECORDS</p><p class="mt-1 text-2xl font-bold">{{ $total }}</p></div>
        <div class="rounded-2xl border bg-white p-4"><p class="text-xs font-bold text-slate-400">PRESENT</p><p class="mt-1 text-2xl font-bold text-emerald-600">{{ $counts['present'] ?? 0 }}</p></div>
        <div class="rounded-2xl border bg-white p-4"><p class="text-xs font-bold text-slate-400">LATE</p><p class="mt-1 text-2xl font-bold text-amber-600">{{ $counts['late'] ?? 0 }}</p></div>
        <div class="rounded-2xl border bg-white p-4"><p class="text-xs font-bold text-slate-400">ABSENT</p><p class="mt-1 text-2xl font-bold text-rose-600">{{ $counts['absent'] ?? 0 }}</p></div>
        <div class="col-span-2 rounded-2xl border bg-white p-4 lg:col-span-1"><p class="text-xs font-bold text-slate-400">ATTENDANCE RATE</p><p class="mt-1 text-2xl font-bold {{ $rate >= 80 ? 'text-emerald-600' : 'text-rose-600' }}">{{ number_format($rate, 1) }}%</p></div>
    </div>

    <section class="overflow-hidden rounded-2xl border bg-white shadow-sm"><header class="border-b px-5 py-4"><h2 class="font-bold">Attendance records</h2><p class="text-xs text-slate-500">Present and late count toward the attendance rate.</p></header><div class="overflow-x-auto"><table class="w-full text-left text-sm"><thead class="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th class="px-4 py-4">Date / time</th><th class="px-4 py-4">Subject / session</th><th class="px-4 py-4">Learner</th><th class="px-4 py-4">Class / stream</th><th class="px-4 py-4">Status</th><th class="px-4 py-4">Recorded by</th></tr></thead><tbody class="divide-y">
        @forelse ($records as $record)
            @php $class = $record->schoolClass ?? $record->student?->schoolClass; $stream = $record->stream ?? $record->student?->stream; @endphp
            <tr><td class="px-4 py-4 font-semibold">{{ $record->attendance_date?->format('d M Y') }}<p class="text-xs font-normal text-slate-400">{{ $record->lesson_time ? \Illuminate\Support\Carbon::parse($record->lesson_time)->format('g:i A') : 'Whole day' }}</p></td><td class="px-4 py-4"><span class="rounded-lg px-2.5 py-1 text-xs font-bold {{ $record->subject ? 'bg-blue-50 text-blue-700' : 'bg-slate-100 text-slate-600' }}">{{ $record->subject?->name ?? 'Daily register' }}</span></td><td class="px-4 py-4 font-semibold">{{ $record->student?->name ?? 'Deleted learner' }}<p class="text-xs font-normal text-slate-400">{{ $record->student?->admission_no }}</p></td><td class="px-4 py-4 text-slate-600">{{ $class?->name ?? '—' }}{{ $stream ? ' · '.$stream->name : '' }}</td><td class="px-4 py-4"><span class="rounded-full px-2.5 py-1 text-xs font-bold {{ match($record->status) { 'present' => 'bg-emerald-100 text-emerald-700', 'late' => 'bg-amber-100 text-amber-700', 'absent' => 'bg-rose-100 text-rose-700', default => 'bg-slate-100 text-slate-600' } }}">{{ ucfirst($record->status) }}</span></td><td class="px-4 py-4 text-slate-500">{{ $record->recorder?->name ?? 'System' }}</td></tr>
        @empty<tr><td colspan="6" class="px-5 py-14 text-center"><p class="font-semibold text-slate-700">No attendance records found</p><p class="mt-1 text-sm text-slate-500">Try a wider date range or clear some filters.</p></td></tr>@endforelse
    </tbody></table></div>@if ($records->hasPages())<div class="border-t px-5 py-4">{{ $records->links() }}</div>@endif</section>
</div>
