<div class="mx-auto max-w-7xl space-y-6">
    <div class="flex flex-wrap items-start justify-between gap-3"><div><h1 class="text-2xl font-bold text-slate-900">Audit trail</h1><p class="mt-1 text-sm text-slate-500">Review page visits, Livewire actions and important school operations performed by staff.</p></div><span class="inline-flex items-center gap-2 rounded-full bg-emerald-100 px-3 py-1.5 text-xs font-bold text-emerald-700"><span class="h-2 w-2 rounded-full bg-emerald-500"></span>Audit capture enabled</span></div>

    <div class="grid gap-4 sm:grid-cols-3"><div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-xs font-bold uppercase tracking-wider text-slate-400">Activities today</p><p class="mt-2 text-3xl font-black text-slate-900">{{ number_format($todayCount) }}</p></div><div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-xs font-bold uppercase tracking-wider text-slate-400">Actions today</p><p class="mt-2 text-3xl font-black text-blue-700">{{ number_format($actionCount) }}</p></div><div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-xs font-bold uppercase tracking-wider text-slate-400">Active staff today</p><p class="mt-2 text-3xl font-black text-emerald-700">{{ number_format($activeUsers) }}</p></div></div>

    <section class="rounded-2xl border border-slate-200 bg-white shadow-sm">
        <div class="grid gap-3 border-b border-slate-100 p-4 md:grid-cols-2 xl:grid-cols-4">
            <input wire:model.live.debounce.350ms="search" class="rounded-xl border-slate-200 text-sm" placeholder="Search event, staff, route or IP">
            <select wire:model.live="userId" class="rounded-xl border-slate-200 text-sm"><option value="">All staff</option>@foreach($users as $member)<option value="{{ $member->id }}">{{ $member->name }} — {{ ucfirst(str_replace('_',' ',$member->role)) }}</option>@endforeach</select>
            <select wire:model.live="role" class="rounded-xl border-slate-200 text-sm"><option value="">All roles</option>@foreach(['admin','superadmin','academic_admin','registrar','teacher','bursar'] as $staffRole)<option value="{{ $staffRole }}">{{ ucfirst(str_replace('_',' ',$staffRole)) }}</option>@endforeach</select>
            <select wire:model.live="event" class="rounded-xl border-slate-200 text-sm"><option value="">All events</option>@foreach($events as $eventName)<option value="{{ $eventName }}">{{ $eventName }}</option>@endforeach</select>
            <label class="text-xs font-bold uppercase text-slate-400">From<input wire:model.live="fromDate" type="date" class="mt-1 block w-full rounded-xl border-slate-200 text-sm font-normal text-slate-700"></label>
            <label class="text-xs font-bold uppercase text-slate-400">To<input wire:model.live="toDate" type="date" class="mt-1 block w-full rounded-xl border-slate-200 text-sm font-normal text-slate-700"></label>
            <div class="flex items-end"><button wire:click="clearFilters" class="w-full rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-bold text-slate-600 hover:bg-slate-50">Clear filters</button></div>
        </div>

        <div class="overflow-x-auto"><table class="w-full min-w-[980px] text-sm"><thead class="bg-slate-50 text-left text-xs uppercase tracking-wide text-slate-500"><tr><th class="px-4 py-3">Date & time</th><th class="px-4 py-3">Staff member</th><th class="px-4 py-3">Event</th><th class="px-4 py-3">Location / action</th><th class="px-4 py-3">IP address</th><th class="px-4 py-3"></th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($logs as $log)@php($meta=$log->metadata ?? [])<tr class="hover:bg-slate-50"><td class="whitespace-nowrap px-4 py-3"><b>{{ $log->created_at->format('d M Y') }}</b><span class="block text-xs text-slate-400">{{ $log->created_at->format('h:i:s A') }}</span></td><td class="px-4 py-3"><b>{{ $log->user?->name ?: 'System' }}</b><span class="block text-xs capitalize text-slate-400">{{ str_replace('_',' ',$log->user?->role ?: 'system') }}</span></td><td class="px-4 py-3"><span class="rounded-full px-2.5 py-1 text-xs font-bold {{ $log->event==='livewire.action' ? 'bg-blue-100 text-blue-700' : (str_contains($log->event,'deleted') ? 'bg-rose-100 text-rose-700' : (str_contains($log->event,'recorded') || str_contains($log->event,'created') ? 'bg-emerald-100 text-emerald-700' : 'bg-slate-100 text-slate-600')) }}">{{ $log->event }}</span></td><td class="max-w-xs px-4 py-3"><b class="block truncate">{{ data_get($meta,'action') ?: data_get($meta,'route') ?: class_basename($log->subject_type ?: '') ?: '—' }}</b><span class="block truncate text-xs text-slate-400">{{ data_get($meta,'component') ?: data_get($meta,'path') ?: ($log->subject_type ? $log->subject_type.' #'.$log->subject_id : 'No additional location') }}</span></td><td class="whitespace-nowrap px-4 py-3 font-mono text-xs text-slate-500">{{ $log->ip_address ?: '—' }}</td><td class="px-4 py-3 text-right"><button wire:click="showDetails({{ $log->id }})" class="rounded-lg border px-3 py-1.5 text-xs font-bold text-slate-600 hover:bg-white">Details</button></td></tr>@empty<tr><td colspan="6" class="px-4 py-14 text-center text-slate-500">No audit activity matches these filters. Clear the filters or perform a staff action and return here.</td></tr>@endforelse</tbody></table></div>
        <div class="border-t border-slate-100 p-4">{{ $logs->links() }}</div>
    </section>

    @if($selectedLog)<div class="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/60 p-4" wire:click.self="closeDetails"><div class="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-2xl bg-white p-6 shadow-2xl"><div class="flex items-start justify-between"><div><h2 class="text-xl font-bold">Audit activity details</h2><p class="mt-1 text-sm text-slate-500">Record #{{ $selectedLog->id }} · {{ $selectedLog->created_at->format('d M Y, h:i:s A') }}</p></div><button wire:click="closeDetails" class="text-2xl text-slate-400">&times;</button></div><div class="mt-5 grid gap-3 sm:grid-cols-2"><div class="rounded-xl bg-slate-50 p-4"><span class="text-xs font-bold uppercase text-slate-400">Staff member</span><p class="mt-1 font-bold">{{ $selectedLog->user?->name ?: 'System' }}</p><p class="text-xs text-slate-500">{{ $selectedLog->user?->email }} · {{ ucfirst(str_replace('_',' ',$selectedLog->user?->role ?: 'system')) }}</p></div><div class="rounded-xl bg-slate-50 p-4"><span class="text-xs font-bold uppercase text-slate-400">Event</span><p class="mt-1 font-bold">{{ $selectedLog->event }}</p><p class="text-xs text-slate-500">IP: {{ $selectedLog->ip_address ?: 'Not available' }}</p></div></div><div class="mt-4 rounded-xl border border-slate-200"><dl class="divide-y divide-slate-100">@forelse(($selectedLog->metadata ?? []) as $key=>$value)<div class="grid gap-1 px-4 py-3 sm:grid-cols-[160px_1fr]"><dt class="text-xs font-bold uppercase text-slate-400">{{ str_replace('_',' ',$key) }}</dt><dd class="break-words text-sm text-slate-700">{{ is_array($value) ? json_encode($value, JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES) : $value }}</dd></div>@empty<div class="p-5 text-sm text-slate-500">No extra metadata was recorded.</div>@endforelse</dl></div>@if($selectedLog->subject_type)<div class="mt-4 text-xs text-slate-500">Related record: {{ $selectedLog->subject_type }} #{{ $selectedLog->subject_id }}</div>@endif</div></div>@endif
</div>