<div class="space-y-6">
    <header class="rounded-3xl bg-slate-900 p-6 text-white shadow-xl"><h1 class="text-2xl font-black text-amber-300">Graduates & Alumni</h1><p class="mt-1 text-sm text-slate-400">Permanent completion records, final balances and certificates.</p></header>
    @if(session('status'))<div class="rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-800">{{ session('status') }}</div>@endif
    <section class="rounded-3xl border bg-white shadow-sm">
        <div class="flex flex-col gap-3 border-b p-5 sm:flex-row"><input wire:model.live.debounce.300ms="search" placeholder="Search graduate or admission number" class="w-full rounded-xl border-slate-200 sm:max-w-md"><select wire:model.live="year" class="rounded-xl border-slate-200"><option value="">All years</option>@foreach($years as $item)<option value="{{ $item }}">{{ $item }}</option>@endforeach</select></div>
        <div class="overflow-x-auto"><table class="w-full text-sm"><thead class="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th class="p-4">Graduate</th><th>Final class</th><th>Completed</th><th>Average</th><th>Balance at exit</th><th>Certificate</th><th>Actions</th></tr></thead><tbody>
        @forelse($graduates as $record)<tr class="border-t"><td class="p-4"><strong>{{ $record->student->name }}</strong><div class="text-xs text-slate-500">{{ $record->student->admission_no }}</div></td><td>{{ $record->schoolClass->name }}</td><td>{{ $record->graduated_at->format('d M Y') }}</td><td>{{ number_format($record->final_average,1) }}%</td><td>UGX {{ number_format($record->outstanding_balance,2) }}</td><td class="font-mono text-xs">{{ $record->certificate_number }}</td><td><div class="flex gap-2"><a href="{{ route('graduates.certificate',$record) }}" class="font-bold text-blue-700">Certificate</a>@if($canManage)<button wire:click="beginReversal({{ $record->id }})" class="font-bold text-rose-700">Reverse</button>@endif</div></td></tr>
        @empty<tr><td colspan="7" class="p-10 text-center text-slate-500">No graduation records found.</td></tr>@endforelse
        </tbody></table></div><div class="border-t p-4">{{ $graduates->links() }}</div>
    </section>
    @if($reversingId)<section class="rounded-2xl border border-rose-200 bg-rose-50 p-5"><h2 class="font-black text-rose-900">Reverse graduation</h2><p class="mt-1 text-xs text-rose-700">This restores the learner and final-term enrolment to active status. The reversal remains audited.</p><div class="mt-3 flex gap-2"><input wire:model="reversalReason" placeholder="Required reason (at least 8 characters)" class="flex-1 rounded-xl border-rose-200"><button wire:click="reverse" class="rounded-xl bg-rose-700 px-4 py-2 font-bold text-white">Confirm reversal</button><button wire:click="$set('reversingId', null)" class="px-3">Cancel</button></div>@error('reversalReason')<p class="mt-1 text-xs text-rose-700">{{ $message }}</p>@enderror</section>@endif
</div>
