<div class="mx-auto max-w-6xl">
    <div class="mb-8"><h1 class="text-2xl font-bold">Learner portal access</h1><p class="text-slate-500">Link a student or parent login to a learner. Links are school-wide identity records, not term transactions.</p></div>
    @if(session('status'))<div class="mb-4 rounded-xl bg-emerald-50 p-3 text-emerald-700">{{ session('status') }}</div>@endif
    <div class="grid gap-6 lg:grid-cols-2">
        <section class="rounded-2xl border bg-white p-6"><h2 class="font-bold">Link an existing login</h2><form wire:submit="linkExisting" class="mt-4 space-y-4"><label class="block text-sm font-semibold">Learner<select wire:model="studentId" class="mt-1 w-full rounded-xl border-slate-200"><option value="">Select learner</option>@foreach($students as $student)<option value="{{ $student->id }}">{{ $student->name }} · {{ $student->admission_no }}</option>@endforeach</select></label><label class="block text-sm font-semibold">Parent or student login<select wire:model="userId" class="mt-1 w-full rounded-xl border-slate-200"><option value="">Select account</option>@foreach($accounts as $account)<option value="{{ $account->id }}">{{ $account->name }} · {{ ucfirst($account->role) }} · {{ $account->email }}</option>@endforeach</select></label><label class="block text-sm font-semibold">Relationship<input wire:model="relationship" class="mt-1 w-full rounded-xl border-slate-200" placeholder="Parent, Guardian, Student"></label><button class="rounded-xl bg-yellow-400 px-5 py-2 font-bold">Link account</button></form></section>
        <section class="rounded-2xl border bg-white p-6"><h2 class="font-bold">Create and link a login</h2><form wire:submit="createAndLink" class="mt-4 grid gap-4 md:grid-cols-2"><label class="block text-sm font-semibold md:col-span-2">Learner<select wire:model="studentId" class="mt-1 w-full rounded-xl border-slate-200"><option value="">Select learner</option>@foreach($students as $student)<option value="{{ $student->id }}">{{ $student->name }} · {{ $student->admission_no }}</option>@endforeach</select></label><label class="block text-sm font-semibold">Account type<select wire:model="role" class="mt-1 w-full rounded-xl border-slate-200"><option value="parent">Parent/guardian</option><option value="student">Student</option></select></label><label class="block text-sm font-semibold">Relationship<input wire:model="relationship" class="mt-1 w-full rounded-xl border-slate-200"></label><label class="block text-sm font-semibold">Name<input wire:model="name" class="mt-1 w-full rounded-xl border-slate-200"></label><label class="block text-sm font-semibold">Email<input wire:model="email" type="email" class="mt-1 w-full rounded-xl border-slate-200"></label><label class="block text-sm font-semibold md:col-span-2">Temporary password<input wire:model="password" type="password" class="mt-1 w-full rounded-xl border-slate-200"><small class="font-normal text-slate-500">Use at least eight characters and share it securely.</small></label><button class="w-max rounded-xl bg-yellow-400 px-5 py-2 font-bold">Create and link</button></form></section>
    </div>
    <section class="mt-6 overflow-hidden rounded-2xl border bg-white"><div class="border-b p-5"><h2 class="font-bold">Current learner links</h2></div><div class="overflow-x-auto"><table class="w-full text-sm"><thead class="bg-slate-50"><tr><th class="p-4 text-left">Learner</th><th class="p-4 text-left">Account</th><th class="p-4">Role</th><th class="p-4">Relationship</th><th></th></tr></thead><tbody>@forelse($links as $link)<tr class="border-t"><td class="p-4"><strong>{{ $link->student_name }}</strong><br><span class="text-slate-500">{{ $link->admission_no }}</span></td><td class="p-4">{{ $link->user_name }}<br><span class="text-slate-500">{{ $link->email }}</span></td><td class="p-4 text-center">{{ ucfirst($link->role) }}</td><td class="p-4 text-center">{{ $link->relationship }}</td><td class="p-4 text-right"><button wire:click="unlink({{ $link->id }})" wire:confirm="Remove this portal link?" class="font-bold text-rose-600">Remove link</button></td></tr>@empty<tr><td colspan="5" class="p-8 text-center text-slate-500">No parent or student accounts are linked yet.</td></tr>@endforelse</tbody></table></div></section>
</div>
