<script src="{{ asset('js/chart.umd.js') }}"></script>
<div class="space-y-6 pb-12">
    @if(!$student)
        <div class="rounded-2xl border border-amber-200 bg-amber-50 p-6 text-amber-900">No learner is linked to this account yet. Please contact the school registrar.</div>
    @else
        @if($graduation)<div class="rounded-2xl border border-blue-200 bg-blue-50 p-4 text-sm text-blue-900"><strong>Graduate read-only portal.</strong> {{ $student->name }} completed {{ $graduation->schoolClass?->name }} in {{ $graduation->graduation_year }}. Historical results and payments remain available; no new academic or fee activity will be created.</div>@endif
        <section class="relative overflow-hidden rounded-2xl p-6 shadow-lg ring-2 ring-yellow-400/20 lg:p-8" style="background: linear-gradient(135deg, #252641 0%, #3a3d6b 100%);">
            <div class="relative z-10 flex flex-wrap items-center justify-between gap-5"><div><h1 class="mb-1 text-2xl font-semibold text-white">Welcome back, {{ explode(' ', auth()->user()->name)[0] }} &#128075;</h1><p class="text-sm text-gray-300">Here's what's happening with {{ $isParent ? $student->name : 'your learning' }} at {{ $school->name }} today.</p><p class="mt-3 text-xs font-medium text-yellow-400">{{ now()->format('l, d F Y · h:i A') }} · {{ $isParent ? 'Parent / guardian' : 'Student' }}</p></div><div class="flex min-w-56 flex-col gap-3">@if($isParent && $students->count() > 1)<label class="text-xs font-bold uppercase tracking-wide text-gray-300">Selected learner<select wire:model.live="selectedStudentId" class="mt-1 w-full rounded-xl border border-white/20 bg-white px-3 py-2 text-sm font-semibold text-slate-900">@foreach($students as $linkedStudent)<option value="{{ $linkedStudent->id }}">{{ $linkedStudent->name }}</option>@endforeach</select></label>@endif<div class="rounded-xl border border-white/15 bg-white/10 px-5 py-3 text-right"><span class="block text-xs uppercase tracking-wide text-gray-300">Admission number</span><b class="text-lg text-yellow-300">{{ $student->admission_no }}</b><span class="block text-xs text-gray-300">{{ $student->schoolClass?->name }}{{ $student->stream ? ' · '. $student->stream->name : '' }}</span></div></div></div>
            <div class="absolute -bottom-10 -right-6 h-40 w-40 rounded-full bg-yellow-400/10"></div><div class="absolute -top-10 right-16 h-24 w-24 rounded-full bg-yellow-400/10"></div>
        </section>

        <div class="grid gap-4 sm:grid-cols-2 {{ $isParent ? 'xl:grid-cols-6' : 'xl:grid-cols-4' }}">
            @if($isParent)
                @foreach([
                    ['Expected fees','UGX '.number_format($fees['expected'],0),'Current term charges'],
                    ['Fees paid','UGX '.number_format($fees['paid'],0),'Verified collections'],
                    ['Balance','UGX '.number_format($fees['balance'],0),'Outstanding amount'],
                ] as [$label,$value,$note])
                    <div class="student-stat rounded-2xl border bg-white p-5"><p class="text-xs font-bold uppercase tracking-wide text-slate-400">{{ $label }}</p><p class="mt-2 text-xl font-bold text-[#252641]">{{ $value }}</p><p class="mt-1 text-xs text-slate-500">{{ $note }}</p></div>
                @endforeach
            @endif
            <div class="student-stat rounded-2xl border bg-white p-5"><p class="text-xs font-bold uppercase tracking-wide text-slate-400">Attendance rate</p><p class="mt-2 text-3xl font-bold text-[#252641]">{{ $studentAttendance->count() ? round(($studentAttendance->whereIn('status',['present','late'])->count() / $studentAttendance->count()) * 100) : 0 }}%</p><p class="mt-1 text-xs text-emerald-600">Current term record</p></div>
            <div class="student-stat rounded-2xl border bg-white p-5"><p class="text-xs font-bold uppercase tracking-wide text-slate-400">Published results</p><p class="mt-2 text-3xl font-bold text-[#252641]">{{ $exams->count() }}</p><p class="mt-1 text-xs text-yellow-700">Available report cards</p></div>
            <div class="student-stat rounded-2xl border bg-white p-5"><p class="text-xs font-bold uppercase tracking-wide text-slate-400">Subjects assessed</p><p class="mt-2 text-3xl font-bold text-[#252641]">{{ $performance->count() }}</p><p class="mt-1 text-xs text-slate-500">Approved marks only</p></div>
        </div>

        <div class="grid gap-5 xl:grid-cols-3">
            <section id="attendance" class="rounded-2xl border bg-white p-5 shadow-sm xl:col-span-2"><div class="flex items-center justify-between"><div><h2 class="font-bold">{{ $isParent ? $student->name.' attendance' : 'My attendance' }}</h2><p class="text-sm text-slate-500">Record for the past seven days.</p></div><span class="rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-700">{{ $studentAttendance->whereIn('status',['present','late'])->count() }} present / late</span></div><div class="mt-5 h-72"><canvas id="studentAttendanceChart"></canvas></div></section>
            <aside class="rounded-2xl border bg-white p-5 shadow-sm"><h2 class="font-bold">Notifications</h2><div class="mt-4 max-h-72 space-y-3 overflow-y-auto">@forelse($notifications->take(7) as $notification)<div class="rounded-xl bg-slate-50 p-3 text-sm"><span class="font-bold capitalize text-yellow-700">{{ $notification['type'] }}</span><p class="mt-1 text-slate-600">{{ $notification['message'] }}</p></div>@empty<p class="text-sm text-slate-500">No notifications right now.</p>@endforelse</div></aside>
        </div>

        <div class="grid gap-5 lg:grid-cols-2">
            <section id="performance" class="rounded-2xl border bg-white p-5 shadow-sm"><h2 class="font-bold">{{ $isParent ? $student->name.' subject performance' : 'My subject performance' }}</h2><p class="text-sm text-slate-500">Only approved marks from this term.</p><div class="mt-5 h-72"><canvas id="studentPerformanceChart"></canvas></div></section>
            <section id="timetable" class="rounded-2xl border bg-white p-5 shadow-sm"><h2 class="font-bold">Today’s timetable</h2><p class="text-sm text-slate-500">{{ now()->format('l') }} · {{ $student->schoolClass?->name }}</p><div class="mt-4 space-y-3">@forelse($timetable as $slot)<div class="flex items-center justify-between rounded-xl border border-slate-100 bg-slate-50 p-3"><span><b>{{ $slot->subject ?: $slot->label ?: 'Study period' }}</b><span class="block text-xs text-slate-500">{{ $slot->label && $slot->subject ? $slot->label : '' }}</span></span><span class="text-sm font-bold text-yellow-700">{{ substr($slot->starts_at,0,5) }}–{{ substr($slot->ends_at,0,5) }}</span></div>@empty<p class="rounded-xl bg-slate-50 p-4 text-sm text-slate-500">No timetable slots have been set for today.</p>@endforelse</div></section>
        </div>

        <div class="grid gap-5 {{ $isParent ? 'xl:grid-cols-3' : 'lg:grid-cols-2' }}">
            <section id="results" class="rounded-2xl border bg-white p-5 shadow-sm"><h2 class="font-bold">Report cards</h2><div class="mt-4 space-y-3">@forelse($exams as $exam)@php($blocked=$feeRule && $student->balance($exam->term)>0)<div class="flex items-center justify-between rounded-xl border p-4"><span><b>{{ $exam->name }}</b><span class="block text-sm text-slate-500">{{ $exam->term->name }}, {{ $exam->term->year }}</span></span>@if($blocked)<span class="text-xs font-bold text-rose-600">Fee clearance required</span>@else<a href="{{ route('exams.report-card',[$exam,$student]) }}" target="_blank" class="rounded-lg bg-yellow-400 px-3 py-2 text-xs font-bold text-slate-900">View report</a>@endif</div>@empty<p class="text-sm text-slate-500">No published report cards yet.</p>@endforelse</div></section>
            <section id="payments" class="rounded-2xl border bg-white p-5 shadow-sm"><div class="flex items-center justify-between"><div><h2 class="font-bold">Recent payments</h2><p class="text-xs text-slate-500">Payments recorded for {{ $student->name }} this term.</p></div></div><div class="mt-4 space-y-3">@forelse($payments->take(6) as $payment)<div class="rounded-xl bg-slate-50 p-3 text-sm"><div class="flex items-start justify-between gap-3"><span><b>{{ ucfirst(str_replace('_',' ', $payment->method)) }}</b><span class="block text-xs text-slate-500">{{ \Carbon\Carbon::parse($payment->paid_at)->format('d M Y') }} · {{ $payment->transaction_id ?: 'Recorded payment' }}</span></span><b class="whitespace-nowrap text-emerald-700">UGX {{ number_format($payment->amount) }}</b></div><a href="{{ route('fee-payments.receipt', $payment->id) }}" target="_blank" class="mt-2 inline-flex rounded-lg border border-slate-200 bg-white px-3 py-1.5 text-xs font-bold text-yellow-700 hover:border-yellow-300 hover:bg-yellow-50">View receipt</a></div>@empty<p class="text-sm text-slate-500">No payments recorded for this term.</p>@endforelse</div></section>
            <section id="events" class="rounded-2xl border bg-white p-5 shadow-sm"><h2 class="font-bold">Upcoming school events</h2><div class="mt-4 space-y-3">@forelse($events as $event)<div class="rounded-xl bg-slate-50 p-3"><b>{{ $event->title }}</b><span class="mt-1 block text-sm text-slate-500">{{ $event->event_date->format('l, d M Y') }}</span></div>@empty<p class="text-sm text-slate-500">No upcoming events.</p>@endforelse</div></section>
        </div>
    @endif
</div>
@if($student)<script>document.addEventListener('livewire:navigated',()=>{const attendance=document.getElementById('studentAttendanceChart');const performance=document.getElementById('studentPerformanceChart');if(attendance&&!attendance.dataset.ready){attendance.dataset.ready='1';new Chart(attendance,{type:'line',data:{labels:@json(collect(range(6,0))->map(fn($offset)=>now()->subDays($offset)->format('D'))->values()),datasets:[{label:'Present / late',data:@json($attendanceSeries),borderColor:'#eab308',backgroundColor:'rgba(234,179,8,.15)',fill:true,tension:.35},{label:'Absent',data:@json($absenceSeries),borderColor:'#ef4444',backgroundColor:'rgba(239,68,68,.1)',fill:true,tension:.35}]},options:{responsive:true,maintainAspectRatio:false,scales:{y:{beginAtZero:true,ticks:{precision:0}}}}});}if(performance&&!performance.dataset.ready){performance.dataset.ready='1';new Chart(performance,{type:'bar',data:{labels:@json($performance->pluck('name')),datasets:[{label:'Average %',data:@json($performance->pluck('average')),backgroundColor:['#facc15','#38bdf8','#a78bfa','#34d399','#fb7185']}]},options:{responsive:true,maintainAspectRatio:false,scales:{y:{beginAtZero:true,max:100}}}});}});document.dispatchEvent(new Event('livewire:navigated'));</script>@endif
