<script src="{{ asset('js/chart.umd.js') }}"></script>
<div class="space-y-6">
    @if(!$student)
        <div class="rounded-2xl border border-amber-200 bg-amber-50 p-6 text-amber-900">Your student account is not linked to a learner yet. Please contact the school registrar.</div>
    @else
        <section class="overflow-hidden rounded-2xl bg-[#252641] p-6 text-white shadow-xl md:p-8"><div class="flex flex-wrap items-start justify-between gap-5"><div><p class="text-sm font-bold uppercase tracking-[.18em] text-yellow-400">Student dashboard</p><h1 class="mt-2 text-3xl font-bold">Good {{ now()->hour < 12 ? 'morning' : (now()->hour < 17 ? 'afternoon' : 'evening') }}, {{ strtok($student->name, ' ') }}!</h1><p class="mt-2 text-slate-300">Here is your personal learning overview for {{ $term?->name }}, {{ $term?->year }}.</p></div><div class="rounded-xl border border-white/15 bg-white/10 px-5 py-3 text-right"><span class="block text-xs uppercase tracking-wide text-slate-300">Admission number</span><b class="text-lg text-yellow-300">{{ $student->admission_no }}</b></div></div></section>
        <div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><div class="student-stat rounded-2xl border bg-white p-5"><p class="text-xs font-bold uppercase tracking-wide text-slate-400">Attendance rate</p><p class="mt-2 text-3xl font-bold text-[#252641]">{{ $studentAttendance->count() ? round(($studentAttendance->whereIn('status',['present','late'])->count() / $studentAttendance->count()) * 100) : 0 }}%</p><p class="mt-1 text-sm text-emerald-600">Personal term record</p></div><div class="student-stat rounded-2xl border bg-white p-5"><p class="text-xs font-bold uppercase tracking-wide text-slate-400">Present / late</p><p class="mt-2 text-3xl font-bold text-[#252641]">{{ $studentAttendance->whereIn('status',['present','late'])->count() }}</p><p class="mt-1 text-sm text-slate-500">Captured attendance days</p></div><div class="student-stat rounded-2xl border bg-white p-5"><p class="text-xs font-bold uppercase tracking-wide text-slate-400">Published results</p><p class="mt-2 text-3xl font-bold text-[#252641]">{{ $exams->where('school_class_id',$student->school_class_id)->count() }}</p><p class="mt-1 text-sm text-yellow-700">Available report cards</p></div><div class="student-stat rounded-2xl border bg-white p-5"><p class="text-xs font-bold uppercase tracking-wide text-slate-400">Subjects assessed</p><p class="mt-2 text-3xl font-bold text-[#252641]">{{ $performance->count() }}</p><p class="mt-1 text-sm text-slate-500">Approved marks only</p></div></div>

        <div class="grid gap-5 xl:grid-cols-3"><section class="rounded-2xl border bg-white p-5 shadow-sm xl:col-span-2"><div class="flex items-center justify-between"><div><h2 class="font-bold">My attendance</h2><p class="text-sm text-slate-500">Personal record for the past seven days.</p></div><span class="rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-700">{{ $studentAttendance->whereIn('status',['present','late'])->count() }} present / late</span></div><div class="mt-5 h-72"><canvas id="studentAttendanceChart"></canvas></div></section><aside class="rounded-2xl border bg-white p-5 shadow-sm"><h2 class="font-bold">Notifications</h2><div class="mt-4 space-y-3">@forelse($notifications->take(5) as $notification)<div class="rounded-xl bg-slate-50 p-3 text-sm"><span class="font-bold capitalize text-yellow-700">{{ $notification['type'] }}</span><p class="mt-1 text-slate-600">{{ $notification['message'] }}</p></div>@empty<p class="text-sm text-slate-500">No notifications right now.</p>@endforelse</div></aside></div>

        <div class="grid gap-5 lg:grid-cols-2"><section class="rounded-2xl border bg-white p-5 shadow-sm"><h2 class="font-bold">My subject performance</h2><p class="text-sm text-slate-500">Only approved marks from this term.</p><div class="mt-5 h-72"><canvas id="studentPerformanceChart"></canvas></div></section><section class="rounded-2xl border bg-white p-5 shadow-sm"><div class="flex items-center justify-between"><div><h2 class="font-bold">Today’s timetable</h2><p class="text-sm text-slate-500">{{ now()->format('l') }} · {{ $student->schoolClass?->name }}</p></div></div><div class="mt-4 space-y-3">@forelse($timetable as $slot)<div class="flex items-center justify-between rounded-xl border border-slate-100 bg-slate-50 p-3"><span><b>{{ $slot->subject ?: $slot->label ?: 'Study period' }}</b><span class="block text-xs text-slate-500">{{ $slot->label && $slot->subject ? $slot->label : '' }}</span></span><span class="text-sm font-bold text-yellow-700">{{ substr($slot->starts_at,0,5) }}–{{ substr($slot->ends_at,0,5) }}</span></div>@empty<p class="rounded-xl bg-slate-50 p-4 text-sm text-slate-500">No timetable slots have been set for today.</p>@endforelse</div></section></div>

        <div class="grid gap-5 lg:grid-cols-2"><section class="rounded-2xl border bg-white p-5 shadow-sm"><h2 class="font-bold">My report cards</h2><div class="mt-4 space-y-3">@forelse($exams->where('school_class_id',$student->school_class_id) as $exam)@php($blocked=$feeRule && $student->balance($exam->term)>0)<div class="flex items-center justify-between rounded-xl border p-4"><span><b>{{ $exam->name }}</b><span class="block text-sm text-slate-500">{{ $exam->term->name }}, {{ $exam->term->year }}</span></span>@if($blocked)<span class="text-xs font-bold text-rose-600">Fee clearance required</span>@else<a href="{{ route('exams.report-card',[$exam,$student]) }}" target="_blank" class="rounded-lg bg-yellow-400 px-3 py-2 text-xs font-bold text-slate-900">View report</a>@endif</div>@empty<p class="text-sm text-slate-500">No published report cards yet.</p>@endforelse</div></section><section class="rounded-2xl border bg-white p-5 shadow-sm"><h2 class="font-bold">Upcoming school events</h2><div class="mt-4 space-y-3">@forelse($events as $event)<div class="rounded-xl bg-slate-50 p-3"><b>{{ $event->title }}</b><span class="mt-1 block text-sm text-slate-500">{{ $event->event_date->format('l, d M Y') }}</span></div>@empty<p class="text-sm text-slate-500">No upcoming events.</p>@endforelse</div></section></div>
    @endif
</div>
@if($student)<script>document.addEventListener('livewire:navigated',()=>{const attendance=document.getElementById('studentAttendanceChart');const performance=document.getElementById('studentPerformanceChart');if(attendance&&!attendance.dataset.ready){attendance.dataset.ready='1';new Chart(attendance,{type:'line',data:{labels:@json(collect(range(6,0))->map(fn($offset)=>now()->subDays($offset)->format('D'))->values()),datasets:[{label:'Present / late',data:@json($attendanceSeries),borderColor:'#eab308',backgroundColor:'rgba(234,179,8,.15)',fill:true,tension:.35},{label:'Absent',data:@json($absenceSeries),borderColor:'#ef4444',backgroundColor:'rgba(239,68,68,.1)',fill:true,tension:.35}]},options:{responsive:true,maintainAspectRatio:false,scales:{y:{beginAtZero:true,ticks:{precision:0}}}}});}if(performance&&!performance.dataset.ready){performance.dataset.ready='1';new Chart(performance,{type:'bar',data:{labels:@json($performance->pluck('name')),datasets:[{label:'Average %',data:@json($performance->pluck('average')),backgroundColor:['#facc15','#38bdf8','#a78bfa','#34d399','#fb7185']}]},options:{responsive:true,maintainAspectRatio:false,scales:{y:{beginAtZero:true,max:100}}}});}});document.dispatchEvent(new Event('livewire:navigated'));</script>@endif
