<div class="mx-auto max-w-7xl">
    <div class="mb-8 flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between">
        <div><p class="text-sm font-bold uppercase tracking-widest text-yellow-700">Academic planner</p><h1 class="mt-1 text-3xl font-bold text-slate-900">Class timetable</h1><p class="mt-2 text-slate-500">Build a weekly schedule for the current term without double-booking a teacher.</p></div>
        <div class="rounded-2xl bg-slate-900 px-5 py-4 text-white"><p class="text-xs uppercase tracking-wider text-slate-400">Working term</p><p class="mt-1 font-bold">{{ $term ? $term->name.', '.$term->year : 'No open term' }}</p></div>
    </div>
    @if(session('status'))<div class="mb-5 rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-emerald-700">{{ session('status') }}</div>@endif
    @if(session('error'))<div class="mb-5 rounded-2xl border border-rose-200 bg-rose-50 p-4 text-rose-700">{{ session('error') }}</div>@endif
    <div class="grid gap-6 xl:grid-cols-[340px_1fr]">
        <aside class="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm">
            <div class="mb-6 flex items-center gap-3"><span class="flex h-9 w-9 items-center justify-center rounded-xl bg-yellow-400 font-bold text-slate-900">+</span><div><h2 class="font-bold">Schedule a slot</h2><p class="text-xs text-slate-500">One lesson, break, or activity.</p></div></div>
            <form wire:submit="saveSlot" class="space-y-4">
                <label class="block text-sm font-semibold text-slate-700">Class<select wire:model.live="classId" class="mt-1.5 w-full rounded-xl border-slate-200 bg-slate-50 px-3 py-2.5"><option value="">Choose class</option>@foreach($classes as $class)<option value="{{ $class->id }}">{{ $class->name }}</option>@endforeach</select></label>
                <label class="block text-sm font-semibold text-slate-700">Stream <span class="font-normal text-slate-400">(optional)</span><select wire:model="streamId" class="mt-1.5 w-full rounded-xl border-slate-200 bg-slate-50 px-3 py-2.5"><option value="">All streams</option>@foreach($streams as $stream)<option value="{{ $stream->id }}">{{ $stream->name }}</option>@endforeach</select></label>
                <div class="grid grid-cols-2 gap-3"><label class="block text-sm font-semibold text-slate-700">Day<select wire:model="day" class="mt-1.5 w-full rounded-xl border-slate-200 bg-slate-50 px-3 py-2.5">@foreach(['Monday','Tuesday','Wednesday','Thursday','Friday'] as $item)<option>{{ $item }}</option>@endforeach</select></label><label class="block text-sm font-semibold text-slate-700">Subject<select wire:model="subjectId" class="mt-1.5 w-full rounded-xl border-slate-200 bg-slate-50 px-3 py-2.5"><option value="">Activity/break</option>@foreach($subjects as $subject)<option value="{{ $subject->id }}">{{ $subject->name }}</option>@endforeach</select></label></div>
                <div class="grid grid-cols-2 gap-3"><label class="block text-sm font-semibold text-slate-700">Starts<input wire:model="startsAt" type="time" class="mt-1.5 w-full rounded-xl border-slate-200 bg-slate-50 px-3 py-2.5"></label><label class="block text-sm font-semibold text-slate-700">Ends<input wire:model="endsAt" type="time" class="mt-1.5 w-full rounded-xl border-slate-200 bg-slate-50 px-3 py-2.5"></label></div>
                <label class="block text-sm font-semibold text-slate-700">Teacher<select wire:model="teacherId" class="mt-1.5 w-full rounded-xl border-slate-200 bg-slate-50 px-3 py-2.5"><option value="">Not assigned</option>@foreach($teachers as $teacher)<option value="{{ $teacher->id }}">{{ $teacher->name }}</option>@endforeach</select></label>
                <label class="block text-sm font-semibold text-slate-700">Custom label <span class="font-normal text-slate-400">(for breaks/assembly)</span><input wire:model="label" placeholder="e.g. Morning break" class="mt-1.5 w-full rounded-xl border-slate-200 bg-slate-50 px-3 py-2.5"></label>
                @error('teacherId')<p class="rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{{ $message }}</p>@enderror
                <button class="w-full rounded-xl bg-slate-900 py-3 font-bold text-white transition hover:bg-slate-700">Add to timetable</button>
            </form>
        </aside>
        <section class="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm">
            <div class="flex flex-col gap-3 border-b border-slate-100 p-6 sm:flex-row sm:items-center sm:justify-between"><div><h2 class="font-bold text-slate-900">Weekly board</h2><p class="mt-1 text-sm text-slate-500">{{ $classes->firstWhere('id', $classId)?->name ?? 'Select a class' }} · click × to remove a slot.</p></div><span class="w-max rounded-full bg-yellow-50 px-3 py-1 text-xs font-bold text-yellow-800">{{ $timetableSlots->count() }} slots</span></div>
            <div class="overflow-x-auto"><table class="min-w-[850px] w-full border-collapse text-sm"><thead><tr class="bg-slate-50 text-xs uppercase tracking-wider text-slate-400"><th class="w-28 border-b p-4 text-left font-bold">Time</th>@foreach(['Monday','Tuesday','Wednesday','Thursday','Friday'] as $day)<th class="border-b p-4 text-left font-bold">{{ substr($day,0,3) }}</th>@endforeach</tr></thead><tbody>@forelse($timetableSlots->groupBy(fn($slot)=>substr($slot->starts_at,0,5).' – '.substr($slot->ends_at,0,5)) as $time=>$timeSlots)<tr><td class="border-b border-slate-100 p-4 align-top font-bold text-slate-500">{{ $time }}</td>@foreach(['Monday','Tuesday','Wednesday','Thursday','Friday'] as $day)@php($slot=$timeSlots->firstWhere('day_of_week',$day))<td class="border-b border-l border-slate-100 p-2 align-top">@if($slot)<div class="group rounded-xl border border-yellow-200 bg-yellow-50 p-3"><div class="flex items-start justify-between gap-2"><strong class="text-slate-900">{{ $slot->subject ?: $slot->label ?: 'Activity' }}</strong><button wire:click="deleteSlot({{ $slot->id }})" wire:confirm="Remove this timetable slot?" class="text-slate-400 opacity-0 transition group-hover:opacity-100 hover:text-rose-600">×</button></div><p class="mt-2 text-xs text-slate-500">{{ $slot->teacher ?: 'Teacher not assigned' }}</p></div>@else<div class="h-16 rounded-xl border border-dashed border-slate-200"></div>@endif</td>@endforeach</tr>@empty<tr><td colspan="6" class="p-16 text-center"><div class="mx-auto max-w-sm"><div class="text-4xl">🗓️</div><h3 class="mt-3 font-bold text-slate-800">Your timetable is empty</h3><p class="mt-1 text-sm text-slate-500">Use the planner on the left to add the first lesson.</p></div></td></tr>@endforelse</tbody></table></div>
        </section>
    </div>
</div>
