<!doctype html>
<html lang="en"><head><meta charset="utf-8"><style>
@page{margin:0}*{box-sizing:border-box}body{margin:0;font-family:DejaVu Sans,sans-serif;color:#172033;background:#fff}
.page{position:fixed;inset:0;height:auto;padding:66px 78px 78px;page-break-inside:avoid;background:#fffefb}.outer-frame{position:absolute;inset:14px;border:4px solid #0b2747}.inner-frame{position:absolute;inset:23px;border:2px solid #0b2747}.gold-frame{position:absolute;inset:30px;border:2px solid #c89b35}.gold{position:absolute;top:30px;left:30px;right:30px;height:7px;background:#0b2747;border-bottom:3px solid #c89b35}
.header{display:table;width:100%;border-bottom:2px solid #c89b35;padding-bottom:18px}.logo,.school-info{display:table-cell;vertical-align:middle}.logo{width:90px}.logo img{max-width:72px;max-height:72px}.logo-mark{width:62px;height:62px;border:3px solid #c89b35;border-radius:50%;text-align:center;line-height:56px;font-family:Georgia,serif;font-size:24px;color:#c89b35}.school-info{text-align:right}.school{font-family:Georgia,serif;font-size:22px;font-weight:bold;color:#0b2747;text-transform:uppercase}.contact{margin-top:5px;font-size:9px;color:#64748b;line-height:1.6}
.date{margin-top:30px;font-size:11px}.title{margin:24px 0 22px;text-align:center;font-family:Georgia,serif;font-size:27px;color:#0b2747;text-transform:uppercase;letter-spacing:2px}.salutation{font-family:Georgia,serif;font-size:14px;font-weight:bold}.body,.closing{margin-top:18px;font-family:Georgia,serif;font-size:13px;line-height:1.85;text-align:justify}.graduate{font-weight:bold;color:#0b2747}.summary{margin:21px 0;padding:14px 18px;border-left:5px solid #c89b35;background:#f8f6ef;font-size:11px;line-height:1.65}.signature{margin-top:42px;width:260px;border-top:1px solid #c89b35;padding-top:7px}.sign-name{font-family:Georgia,serif;font-size:14px;font-weight:bold}.sign-title{margin-top:3px;color:#a57920;font-size:9px;text-transform:uppercase;letter-spacing:1px}.footer{position:absolute;left:58px;right:58px;bottom:34px;border-top:1px solid #d7dee8;padding-top:10px;font-size:8px;color:#64748b}.ref{float:right;color:#0b2747;font-weight:bold}
</style></head><body>
@php($signatory=$settings['certificate_signatory_name']??$record->school->principal_name)
<div class="page"><div class="outer-frame"></div><div class="inner-frame"></div><div class="gold-frame"></div><div class="gold"></div>
<div class="header"><div class="logo">@if($badgeDataUri)<img src="{{ $badgeDataUri }}" alt="School badge">@else<div class="logo-mark">E</div>@endif</div><div class="school-info"><div class="school">{{ $record->school->name }}</div><div class="contact">{{ $record->school->address }}<br>{{ collect([$record->school->phone,$record->school->email,$record->school->website])->filter()->join(' - ') }}</div></div></div>
<div class="date">{{ now()->format('d F Y') }}</div><div class="title">{{ $settings['recommendation_title']??'Letter of Recommendation' }}</div><div class="salutation">{{ $settings['recommendation_intro']??'To Whom It May Concern' }},</div>
<div class="body">{{ $settings['recommendation_body']??'We are pleased to recommend this graduate, who completed their studies at our institution with commitment, discipline, and good standing.' }} This letter confirms that <span class="graduate">{{ $record->student->name }}</span> successfully completed {{ $record->schoolClass->name }} at {{ $record->school->name }} in the {{ $record->graduation_year }} academic year.</div>
<div class="summary"><strong>Graduate:</strong> {{ $record->student->name }}<br><strong>Admission number:</strong> {{ $record->student->admission_no }}<br><strong>Final class:</strong> {{ $record->schoolClass->name }}<br><strong>Final average:</strong> {{ number_format($record->final_average,1) }}%<br><strong>Certificate number:</strong> {{ $record->certificate_number }}</div>
<div class="closing">{{ $settings['recommendation_closing']??'We confidently recommend them for further study and suitable opportunities.' }}</div><div class="signature"><div class="sign-name">{{ $signatory?:'Authorized Signatory' }}</div><div class="sign-title">{{ $settings['certificate_signatory_title']??'Head Teacher' }}</div></div><div class="footer">Issued by {{ $record->school->name }}<span class="ref">Reference: {{ $record->certificate_number }}</span></div></div>
</body></html>
