<!doctype html><html><head><meta charset="utf-8"><title>{{ ucfirst($type) }} ID Cards</title><style>
@page{margin:9mm}*{box-sizing:border-box}body{margin:0;font-family:DejaVu Sans,sans-serif;color:#10213d}.card{display:inline-block;position:relative;vertical-align:top;width:54mm;height:85.6mm;margin:2.2mm 2.7mm;border:.35mm solid #d7dee8;border-radius:4mm;overflow:hidden;background:#fff}.top{height:27mm;background:#0b315f;color:#fff;text-align:center;padding:5mm 3mm 0}.wave{position:absolute;left:-8mm;top:20mm;width:70mm;height:15mm;background:#eab308;transform:rotate(-8deg)}.wave2{position:absolute;left:-8mm;top:23mm;width:70mm;height:15mm;background:#eef6ff;transform:rotate(-8deg)}.brand{position:relative;z-index:2}.logo{display:inline-block;vertical-align:middle;width:10mm;height:10mm;border-radius:50%;background:#fff;padding:1mm;color:#0b315f;font-size:6mm;font-weight:bold;line-height:8mm}.logo img{width:8mm;height:8mm;object-fit:contain}.school{display:inline-block;vertical-align:middle;width:34mm;margin-left:1.5mm;text-align:left}.school h1{margin:0;font-size:3.3mm;line-height:3.8mm;text-transform:uppercase}.school p{margin:1mm 0 0;color:#fde68a;font-size:1.65mm}.photo-wrap{position:absolute;z-index:4;top:28mm;left:16mm;width:22mm;height:25mm;border:.8mm solid #fff;border-radius:3mm;background:#e8edf4;overflow:hidden;box-shadow:0 1mm 2mm rgba(0,0,0,.18);text-align:center}.photo{width:100%;height:100%;object-fit:cover}.initial{font-size:11mm;font-weight:bold;color:#64748b;line-height:25mm}.content{position:absolute;top:54mm;left:3.5mm;right:3.5mm;text-align:center}.name{font-size:3.5mm;line-height:4mm;font-weight:900;text-transform:uppercase;color:#0b315f}.subtitle{margin-top:1mm;font-size:2.1mm;font-weight:bold;color:#334155}.details{margin-top:2mm;width:100%;font-size:1.8mm;line-height:2.7mm;text-align:left}.details td:first-child{width:17mm;font-weight:bold}.qr{position:absolute;right:3.5mm;bottom:5mm;width:11mm;height:11mm}.qr img{width:100%;height:100%}.signature{position:absolute;left:3.5mm;bottom:6mm;width:27mm;text-align:center;font-family:cursive;font-size:2.2mm}.signature span{display:block;border-top:.25mm solid #334155;margin-top:1mm;padding-top:.5mm;font-family:DejaVu Sans;font-size:1.5mm;font-weight:bold}.footer{position:absolute;bottom:0;left:0;right:0;height:3.5mm;background:#0b315f;color:#fff;text-align:center;font-size:1.6mm;font-weight:bold;line-height:3.5mm}.page-break{page-break-after:always}
</style></head><body>
@php($badgePath = $school->badge_path ? public_path('storage/'.ltrim($school->badge_path, '/')) : null)
@foreach($cards as $index => $card) @php($person = $card['person']) @php($photoPath = $type === 'student' ? ($person->photo_path ? public_path('storage/'.ltrim($person->photo_path, '/')) : null) : ($person->avatar_path ? public_path('storage/'.ltrim($person->avatar_path, '/')) : null))
<article class="card"><div class="top"><div class="brand"><div class="logo">@if($badgePath && is_file($badgePath))<img src="{{ $badgePath }}">@else{{ strtoupper(substr($school->name, 0, 1)) }}@endif</div><div class="school"><h1>{{ $school->name }}</h1><p>{{ $school->motto ?: 'Knowledge · Integrity · Excellence' }}</p></div></div></div><div class="wave"></div><div class="wave2"></div>
<div class="photo-wrap">@if($photoPath && is_file($photoPath))<img class="photo" src="{{ $photoPath }}">@else<div class="initial">{{ strtoupper(substr($person->name, 0, 1)) }}</div>@endif</div>
<div class="content"><div class="name">{{ $person->name }}</div><div class="subtitle">{{ $type === 'student' ? trim(($person->schoolClass?->name ?? '').' '.($person->stream?->name ?? '')) : ($person->designation?->name ?: str($person->role)->replace('_', ' ')->title()) }}</div><table class="details">@if($type === 'student')<tr><td>Admission No.</td><td>: {{ $person->admission_no }}</td></tr><tr><td>Date of Birth</td><td>: {{ $person->date_of_birth?->format('d-m-Y') ?: '—' }}</td></tr><tr><td>Blood Group</td><td>: {{ $person->blood_group ?: '—' }}</td></tr>@else<tr><td>Staff No.</td><td>: {{ $person->staff_number ?: '—' }}</td></tr><tr><td>Role</td><td>: {{ str($person->role)->replace('_', ' ')->title() }}</td></tr><tr><td>Phone</td><td>: {{ $person->phone ?: '—' }}</td></tr>@endif</table></div>
<div class="signature">{{ $school->principal_name ?: 'Head Teacher' }}<span>Authorised Signature</span></div><div class="qr"><img src="{{ $card['qr'] }}"></div><div class="footer">ID NO. {{ $type === 'student' ? $person->admission_no : ($person->staff_number ?: str_pad($person->id, 5, '0', STR_PAD_LEFT)) }} · {{ now()->year }}</div></article>@if(($index + 1) % 9 === 0 && ! $loop->last)<div class="page-break"></div>@endif
@endforeach</body></html>
