<!DOCTYPE html><html lang="en"><head><link rel="icon" type="image/png" href="{{ asset('img/fav.png') }}"><link rel="apple-touch-icon" href="{{ asset('img/fav.png') }}"><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="csrf-token" content="{{ csrf_token() }}"><title>{{ $title ?? 'Platform Dashboard' }} · Edlink</title><link rel="preconnect" href="https://fonts.googleapis.com"><link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700;800&display=swap" rel="stylesheet"><script src="https://cdn.tailwindcss.com"></script><script>tailwind.config={theme:{extend:{fontFamily:{sans:['Poppins','sans-serif']},colors:{edlink:'#facc15'}}}}</script><style>body{font-family:Poppins,sans-serif}.platform-scroll::-webkit-scrollbar{width:5px}.platform-scroll::-webkit-scrollbar-thumb{background:#334155;border-radius:99px}</style></head>
<body class="min-h-screen bg-slate-100 text-slate-900"><div id="sidebar-overlay" onclick="togglePlatformNav()" class="fixed inset-0 z-30 hidden bg-slate-900/70 backdrop-blur-sm lg:hidden"></div>
<aside id="platform-sidebar" class="platform-scroll fixed inset-y-0 left-0 z-40 flex w-72 -translate-x-full flex-col overflow-y-auto bg-slate-900 text-white shadow-2xl transition-transform duration-200 lg:translate-x-0"><div class="flex h-20 items-center gap-3 border-b border-white/10 px-6"><span class="flex h-10 w-10 items-center justify-center rounded-xl bg-yellow-400 font-black text-slate-900">E</span><div><b class="block text-lg">Edlink</b><span class="text-[10px] font-semibold uppercase tracking-[.18em] text-slate-400">Platform control</span></div></div>
@php($menus=[
['Overview',[['Dashboard','platform.dashboard',true]]],
['Platform management',[['Schools','platform.schools',true],['School groups','platform.groups.index',true],['Licences & plans','platform.licences',true],['Billing & renewals','platform.billing',true]]],
['Operations',[['Website content','platform.website.edit',true],['Support centre','platform.support.index',true],['Platform audit','platform.audit',true],['Database backups','platform.backups',true]]],
['Administration',[['Platform administrators','platform.administrators',true],['System settings','platform.settings',true]]]
])
<nav class="flex-1 space-y-6 px-4 py-6">@foreach($menus as [$heading,$items])<div><p class="mb-2 px-3 text-[10px] font-bold uppercase tracking-[.18em] text-slate-500">{{ $heading }}</p><div class="space-y-1">@foreach($items as [$label,$route,$live])@php($active=$route&&request()->routeIs($route)) @if($live)<a href="{{ route($route) }}" class="flex items-center justify-between rounded-xl px-3.5 py-3 text-sm font-semibold transition {{ $active?'bg-yellow-400 text-slate-900 shadow-lg shadow-yellow-400/10':'text-slate-300 hover:bg-white/5 hover:text-white' }}"><span class="flex items-center gap-3"><span class="h-2 w-2 rounded-full {{ $active?'bg-slate-900':'bg-yellow-400' }}"></span>{{ $label }}</span></a>@else<button type="button" class="flex w-full items-center justify-between rounded-xl px-3.5 py-3 text-left text-sm font-medium text-slate-500 hover:bg-white/5"><span class="flex items-center gap-3"><span class="h-2 w-2 rounded-full bg-slate-600"></span>{{ $label }}</span><span class="rounded-full border border-white/10 px-1.5 py-0.5 text-[8px] font-bold uppercase">Soon</span></button>@endif @endforeach</div></div>@endforeach</nav>
<div class="border-t border-white/10 p-4"><div class="mb-3 flex items-center gap-3 rounded-xl bg-white/5 p-3"><span class="flex h-9 w-9 items-center justify-center rounded-xl bg-yellow-400 font-bold text-slate-900">{{ strtoupper(substr(auth('platform')->user()->name,0,1)) }}</span><div class="min-w-0"><b class="block truncate text-xs">{{ auth('platform')->user()->name }}</b><span class="block truncate text-[10px] capitalize text-slate-400">{{ str_replace('_',' ',auth('platform')->user()->role) }}</span></div></div><form method="POST" action="{{ route('platform.logout') }}">@csrf<button class="w-full rounded-xl px-3 py-2.5 text-left text-xs font-bold text-slate-400 hover:bg-rose-500/10 hover:text-rose-300">Secure sign out</button></form></div></aside>
<div class="min-h-screen lg:pl-72"><header class="sticky top-0 z-20 flex h-20 items-center justify-between border-b border-slate-200 bg-white/90 px-5 backdrop-blur-xl sm:px-8"><div class="flex items-center gap-3"><button onclick="togglePlatformNav()" class="flex h-10 w-10 items-center justify-center rounded-xl border border-slate-200 lg:hidden">☰</button><div><h1 class="text-base font-bold sm:text-lg">{{ $title ?? 'Platform Dashboard' }}</h1><p class="hidden text-xs text-slate-400 sm:block">Edlink-wide operations and administration</p></div></div><span class="hidden items-center gap-2 rounded-full bg-yellow-100 px-3 py-2 text-[10px] font-bold text-slate-900 sm:inline-flex"><span class="h-2 w-2 rounded-full bg-yellow-400"></span>Secure session</span></header><main class="p-5 sm:p-8">@yield('content')</main></div><script>function togglePlatformNav(){document.getElementById('platform-sidebar').classList.toggle('-translate-x-full');document.getElementById('sidebar-overlay').classList.toggle('hidden')}</script></body></html>
