<!doctype html>
<html><head><meta charset="utf-8"><style>
@page{margin:92px 34px 46px}*{box-sizing:border-box}html,body{background:#fff}body{font-family:DejaVu Sans,sans-serif;color:#172554;font-size:9px;margin:0}.header{position:fixed;top:-70px;left:0;right:0;border-bottom:3px solid #facc15;padding-bottom:10px}.brand{font-size:18px;font-weight:bold}.title{font-size:13px;font-weight:bold;margin-top:3px;color:#334155}.meta{float:right;text-align:right;color:#64748b;font-size:8px;line-height:1.5}.footer{position:fixed;bottom:-30px;left:0;right:0;border-top:1px solid #cbd5e1;padding-top:7px;color:#64748b;font-size:7px}.footer .right{float:right}.summary{margin-bottom:14px;padding:9px 11px;background:#f8fafc;border-left:4px solid #facc15;color:#475569}.summary b{color:#172554}table{border-collapse:collapse;width:100%;table-layout:auto;background:#fff}thead{display:table-header-group}tr{page-break-inside:avoid;background:#fff}th{background:#172554;color:#fff;text-transform:uppercase;font-size:7px;letter-spacing:.3px;padding:7px 5px;text-align:left}td{padding:6px 5px;border-bottom:1px solid #e2e8f0;vertical-align:top}tbody tr:nth-child(even){background:#f8fafc}.num{text-align:right;white-space:nowrap}.empty{text-align:center;padding:35px;color:#64748b}.cert{margin-top:18px;border-top:1px solid #cbd5e1;padding-top:9px;color:#64748b;font-size:7px}
</style></head><body>
<header class="header"><div class="meta">Generated {{ $generatedAt->format('d M Y, H:i') }}<br>Currency: {{ $currency }}</div><div class="brand">{{ $school->name }}</div><div class="title">{{ $title }}</div></header>
<footer class="footer">Edlink Accounting - Confidential audit document <span class="right">{{ $school->school_number }}</span></footer>
<div class="summary"><b>Reporting period:</b> {{ $from ? date('d M Y',strtotime($from)) : 'Beginning of records' }} to {{ $to ? date('d M Y',strtotime($to)) : 'Current date' }} &nbsp; | &nbsp; <b>Rows:</b> {{ count($rows) }} &nbsp; | &nbsp; <b>Basis:</b> Posted accounting records unless otherwise stated</div>
<table><thead><tr>@foreach($columns as $index=>$column)<th class="{{ in_array($index,$currencyColumns,true)?'num':'' }}">{{ $column }}</th>@endforeach</tr></thead><tbody>
@forelse($rows as $row)<tr>@foreach($row as $index=>$value)<td class="{{ in_array($index,$currencyColumns,true)?'num':'' }}">{{ in_array($index,$currencyColumns,true) && is_numeric($value) ? $currency.' '.number_format((float)$value,2) : $value }}</td>@endforeach</tr>@empty<tr><td colspan="{{ count($columns) }}" class="empty">No records match this reporting period.</td></tr>@endforelse
</tbody></table><div class="cert">Prepared from the system ledger. Verify supporting documents, approvals, bank statements, and physical evidence as part of the audit process.</div>
</body></html>
